# PacketArch — OT Traffic Simulation Platform
# Copyright (c) 2026 Rocky Smith <rocky.d.smith@proton.me>
# Licensed under GPL-3.0. See LICENSE at the repo root.
"""Audit re-sourced CVE records (2026-05-31 CVE/device realism audit, phase D).

Each record was re-sourced from NVD/CISA during the audit and replaces a
fabricated or wrong-product assignment. vulnerable_variants is intentionally
empty (we do not synthesize identity payloads). See tasks/cve-attack-device-audit.md."""
from datetime import datetime

AUDIT_RESOURCED_CVES: list[dict] = [
    {
        "cve_id": "CVE-2017-14470",
        "title": "Rockwell MicroLogix 1400 Series B Improper Access Control",
        "description": "An access-control flaw in Allen-Bradley/Rockwell Automation MicroLogix 1400 Series B controllers (firmware FRN 21.2 and earlier) allows an unauthenticated remote attacker to send crafted packets that trigger read/write operations. This can expose sensitive information, alter device configuration settings, or modify the ladder-logic program on the controller.",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "vendor": "Rockwell",
        "product_family": "MicroLogix",
        "affected_models": ["1766-L32BWA", "MicroLogix 1400 Series B"],
        "affected_firmware_min": None,
        "affected_firmware_max": "21.2",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://www.cisa.gov/news-events/ics-advisories/icsa-17-115-04",
        "references": ["https://nvd.nist.gov/vuln/detail/CVE-2017-14470"],
        "mitre_techniques": ["T0843", "T0836"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2018, 4, 5),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2018-19282",
        "title": "Rockwell PowerFlex 525 AC Drives CIP Stack Denial-of-Service (ICSA-19-087-01)",
        "description": "Rockwell Automation PowerFlex 525 AC drives with embedded EtherNet/IP and Safety (firmware version 5.001 and earlier) are vulnerable to a denial-of-service. A remote unauthenticated attacker can repeatedly send specific CIP packets that crash the CIP network stack, preventing acceptance of new connections (existing connections persist), which can block legitimate users from regaining control of the device. CISA ICSA-19-087-01 assigns CVSS v3 7.5; the NVD primary legacy score is 9.8.",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "PowerFlex",
        "affected_models": ["25B-D030N104", "PowerFlex 525"],
        "affected_firmware_min": None,
        "affected_firmware_max": "5.001",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://www.cisa.gov/news-events/ics-advisories/icsa-19-087-01",
        "references": ["https://nvd.nist.gov/vuln/detail/CVE-2018-19282"],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2019, 4, 4),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2020-6998",
        "title": "Rockwell CompactLogix/ControlLogix Infinite Loop Denial-of-Service",
        "description": "An insufficient control-flow management flaw in Rockwell Automation CompactLogix 5370 and ControlLogix 5570 controllers (firmware versions 33 and earlier) can be triggered by an unauthenticated remote attacker sending specially crafted CIP packets, causing an infinite loop condition. This results in a denial-of-service that disrupts the controller's communications with other networked systems.",
        "severity": "high",
        "cvss_score": 8.6,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "ControlLogix / CompactLogix",
        "affected_models": ["1756-L73", "1769-L33ER", "1769-L24ER-QB1B", "CompactLogix 5370", "ControlLogix 5570"],
        "affected_firmware_min": None,
        "affected_firmware_max": "33",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://nvd.nist.gov/vuln/detail/CVE-2020-6998",
        "references": [],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2022, 7, 27),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2022-1737",
        "title": "Rockwell 1734-AENT POINT I/O EtherNet/IP Adapter Out-of-Bounds Write DoS (ICSA-23-236-06)",
        "description": "An out-of-bounds write vulnerability in the EtherNet/IP stack used by Rockwell Automation 1734-AENT/1734-AENTR Series B POINT I/O adapters (firmware 5.019 and prior) allows an unauthenticated remote attacker to send a specially crafted packet that triggers a denial-of-service condition on the device. The underlying flaw originates in the Pyramid Solutions NetStax EtherNet/IP Adapter kit (NVD-tracked root cause). CISA advisory ICSA-23-236-06 scopes the Rockwell-product impact as a scope-changed availability DoS.",
        "severity": "high",
        "cvss_score": 8.6,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "POINT I/O",
        "affected_models": ["1734-AENT", "1734-AENTR"],
        "affected_firmware_min": None,
        "affected_firmware_max": "5.019",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://www.cisa.gov/news-events/ics-advisories/icsa-23-236-06",
        "references": ["https://nvd.nist.gov/vuln/detail/CVE-2022-1737"],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2022, 7, 12),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2022-3157",
        "title": "Rockwell Logix Controllers Malformed CIP Request Denial-of-Service",
        "description": "Multiple Rockwell Automation Logix controllers are vulnerable to a denial-of-service condition when an unauthenticated remote attacker sends a malformed CIP (Common Industrial Protocol) request. Successful exploitation causes the controller to experience a major non-recoverable fault, halting operations. Affected lines include CompactLogix 5370 and ControlLogix 5570 firmware versions 20 through 33.",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "ControlLogix / CompactLogix",
        "affected_models": ["1756-L73", "1769-L33ER", "1769-L24ER-QB1B", "CompactLogix 5370", "ControlLogix 5570"],
        "affected_firmware_min": "20",
        "affected_firmware_max": "33",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://nvd.nist.gov/vuln/detail/CVE-2022-3157",
        "references": [],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2022, 12, 16),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2022-3166",
        "title": "Rockwell MicroLogix 1100/1400 Webserver Denial-of-Service",
        "description": "A denial-of-service vulnerability exists in the embedded web server of Rockwell Automation MicroLogix 1100 and 1400 controllers. An attacker with network access can send TCP packets to the web server and close the connection abruptly, causing the web server application to become unavailable. No specific firmware versions are enumerated as fixed in the CVE record.",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "MicroLogix",
        "affected_models": ["1766-L32BWA", "MicroLogix 1100", "MicroLogix 1400"],
        "affected_firmware_min": None,
        "affected_firmware_max": None,
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://nvd.nist.gov/vuln/detail/CVE-2022-3166",
        "references": [],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2022, 12, 16),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2023-2071",
        "title": "Rockwell FactoryTalk View ME on PanelView Plus Remote Code Execution (ICSA-23-264-06)",
        "description": "Rockwell Automation FactoryTalk View Machine Edition running on PanelView Plus (versions up to and including 13.0) contains an improper input validation flaw in a CIP class function that restricts library execution. An unauthenticated remote attacker can upload a malicious custom library to bypass the restriction and execute arbitrary code on the device.",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "vendor": "Rockwell",
        "product_family": "PanelView Plus",
        "affected_models": ["2711P-T15C22D9P", "PanelView Plus 7", "FactoryTalk View Machine Edition"],
        "affected_firmware_min": None,
        "affected_firmware_max": "13.0",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://www.cisa.gov/news-events/ics-advisories/icsa-23-264-06",
        "references": ["https://nvd.nist.gov/vuln/detail/CVE-2023-2071"],
        "mitre_techniques": ["T0822", "T0843"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2023, 9, 12),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2023-29464",
        "title": "Rockwell FactoryTalk Linx Memory Disclosure and Denial-of-Service",
        "description": "Rockwell Automation FactoryTalk Linx (versions 6.20 and 6.30), used on PanelView Plus and other HMI/communications stacks, allows an unauthenticated attacker to read data from memory via crafted malicious packets. Oversized packets trigger memory leakage leading to information disclosure, and can render CIP communications unresponsive (denial-of-service).",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "FactoryTalk Linx",
        "affected_models": ["2711P-T15C22D9P", "PanelView Plus 7", "FactoryTalk Linx"],
        "affected_firmware_min": "6.20",
        "affected_firmware_max": "6.30",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-29464",
        "references": [],
        "mitre_techniques": ["T0814", "T0882"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2023, 10, 13),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2024-6077",
        "title": "Rockwell Logix Controllers CIP Security Object Denial-of-Service (SD1963)",
        "description": "A denial-of-service vulnerability exists in Rockwell Automation Logix controllers including ControlLogix 5580 when processing specially crafted network packets targeting the CIP Security Object. Successful exploitation renders the affected device unavailable, and recovery requires a factory reset. Tracked by Rockwell security advisory SD1963.",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "ControlLogix / CompactLogix / GuardLogix",
        "affected_models": ["1756-L83E", "ControlLogix 5580", "CompactLogix 5380", "CompactLogix 5480", "GuardLogix 5580"],
        "affected_firmware_min": "32.011",
        "affected_firmware_max": "33.011",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6077",
        "references": [],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2024, 9, 12),
        "vulnerable_variants": [],
    },
    {
        "cve_id": "CVE-2024-6207",
        "title": "Rockwell Logix Controllers DoS via Crafted CIP Message (SD1707)",
        "description": "A denial-of-service vulnerability affects multiple Rockwell Automation Logix controllers including ControlLogix 5580. An unauthenticated remote attacker can send specially crafted CIP messages that terminate connections to connected devices and deny legitimate access. Recovery requires a firmware download, interrupting controller operations. Tracked by Rockwell security advisory SD1707.",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "vendor": "Rockwell",
        "product_family": "ControlLogix / CompactLogix / GuardLogix",
        "affected_models": ["1756-L83E", "ControlLogix 5580", "CompactLogix 5380", "CompactLogix 5480", "GuardLogix 5580"],
        "affected_firmware_min": "28.011",
        "affected_firmware_max": "34.014",
        "fixed_firmware_version": None,
        "cyber_vision_detectable": True,
        "detection_method": "protocol_identity",
        "advisory_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6207",
        "references": [],
        "mitre_techniques": ["T0814"],
        "exploit_available": False,
        "exploit_complexity": "low",
        "published_date": datetime(2024, 10, 14),
        "vulnerable_variants": [],
    },
]
