#!/usr/bin/env bash
# PacketArch offline installer.
#
# Idempotent. Safe to re-run for upgrades (pass --upgrade to skip secret
# generation and docker-compose up). Never overwrites an existing .env
# unless --force-env is given.

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/packetarch}"
UPGRADE=0
FORCE_ENV=0

usage() {
    cat <<EOF
Usage: sudo ./install.sh [--upgrade] [--force-env] [--install-dir PATH]

  --upgrade        Load new images and restart; preserve existing .env + volumes.
  --force-env      Overwrite an existing .env (generates new secrets — breaks
                   existing logins and database access!).
  --install-dir    Where to place the PacketArch installation (default: ${INSTALL_DIR}).
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --upgrade)      UPGRADE=1 ; shift ;;
        --force-env)    FORCE_ENV=1 ; shift ;;
        --install-dir)  INSTALL_DIR="$2" ; shift 2 ;;
        -h|--help)      usage ; exit 0 ;;
        *)              echo "Unknown arg: $1" >&2 ; usage ; exit 1 ;;
    esac
done

# --- prechecks ----------------------------------------------------------
if [[ "$(id -u)" -ne 0 ]]; then
    echo "ERROR: install.sh must run as root (use sudo)." >&2
    exit 1
fi
command -v docker >/dev/null || { echo "ERROR: Docker not installed." >&2; exit 1; }
docker compose version >/dev/null 2>&1 || {
    echo "ERROR: Docker Compose plugin missing." >&2; exit 1; }

SRC_DIR="$(cd "$(dirname "$0")" && pwd)"
[[ -f "${SRC_DIR}/VERSION" ]] || {
    echo "ERROR: run install.sh from the extracted release directory." >&2
    exit 1
}
# shellcheck disable=SC1091
source "${SRC_DIR}/VERSION"

echo "================================================================"
echo "  PacketArch ${PACKETARCH_VERSION} (build ${BUILD_COMMIT})"
echo "  install-dir: ${INSTALL_DIR}"
echo "  mode:        $([[ ${UPGRADE} -eq 1 ]] && echo upgrade || echo fresh install)"
echo "================================================================"

mkdir -p "${INSTALL_DIR}"

# --- stage files --------------------------------------------------------
echo "[1/5] Staging files in ${INSTALL_DIR}..."
cp "${SRC_DIR}/docker-compose.yml" "${INSTALL_DIR}/docker-compose.yml"
cp "${SRC_DIR}/VERSION"            "${INSTALL_DIR}/VERSION"
cp "${SRC_DIR}/LICENSE"            "${INSTALL_DIR}/LICENSE"
cp "${SRC_DIR}/NOTICE"             "${INSTALL_DIR}/NOTICE"
[[ -f "${SRC_DIR}/THIRD_PARTY_LICENSES.md" ]] && \
    cp "${SRC_DIR}/THIRD_PARTY_LICENSES.md" "${INSTALL_DIR}/THIRD_PARTY_LICENSES.md"
mkdir -p "${INSTALL_DIR}/docker"
cp "${SRC_DIR}/docker/init-db.sql" "${INSTALL_DIR}/docker/init-db.sql"

# --- load images --------------------------------------------------------
echo "[2/5] Loading Docker images (this can take a minute)..."
for img in "${SRC_DIR}/images/"*.tar.gz; do
    [[ -f "$img" ]] || continue
    echo "  loading $(basename "$img") ..."
    gunzip -c "$img" | docker load
done

# --- generate .env (skip on upgrade unless --force-env) -----------------
ENV_FILE="${INSTALL_DIR}/.env"
if [[ -f "${ENV_FILE}" && ${FORCE_ENV} -eq 0 ]]; then
    echo "[3/5] .env exists — preserving. Use --force-env to regenerate."
elif [[ ${UPGRADE} -eq 1 && ! -f "${ENV_FILE}" ]]; then
    echo "ERROR: --upgrade but no existing .env in ${INSTALL_DIR}." >&2
    echo "       Did you mean a fresh install? Drop --upgrade." >&2
    exit 1
else
    echo "[3/5] Generating .env with fresh secrets..."
    POSTGRES_PW="$(openssl rand -hex 16)"
    SECRET_KEY="$(openssl rand -hex 32)"
    ENCRYPTION_KEY="$(openssl rand -base64 32)"
    ADMIN_PW="$(openssl rand -base64 12 | tr -d '+/=' | cut -c1-16)"

    cat > "${ENV_FILE}" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Treat this file like any other secret material.

POSTGRES_PASSWORD=${POSTGRES_PW}
SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
ADMIN_PASSWORD=${ADMIN_PW}

# Feature flags
AI_ENABLED=false

# Build metadata (read by backend for /api/v1/about)
BUILD_COMMIT=${BUILD_COMMIT}
BUILD_DATE=${BUILD_DATE}

# Debug off in production
DEBUG=false
EOF
    chmod 600 "${ENV_FILE}"
    SHOW_ADMIN_PW=1
fi

# --- bring it up --------------------------------------------------------
echo "[4/5] Starting stack..."
cd "${INSTALL_DIR}"
docker compose --env-file .env up -d

echo "[5/5] Waiting for backend healthcheck..."
for i in $(seq 1 30); do
    if docker compose ps backend 2>/dev/null | grep -q "healthy"; then
        echo "  backend healthy after ${i}0s."
        break
    fi
    sleep 10
    [[ $i -eq 30 ]] && echo "  backend not yet healthy after 5 minutes — check \`docker compose logs backend\`" >&2
done

echo ""
echo "================================================================"
echo "  PacketArch installed at ${INSTALL_DIR}"
if [[ "${SHOW_ADMIN_PW:-0}" -eq 1 ]]; then
    echo ""
    echo "  Login:     admin"
    echo "  Password:  ${ADMIN_PW:-<see .env>}"
    echo ""
    echo "  SAVE THESE CREDENTIALS — the admin password is only shown once."
fi
echo ""
echo "  Open:      https://$(hostname -I | awk '{print $1}')/"
echo "             (accept self-signed certificate)"
echo ""
echo "  Logs:      docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f"
echo "  Stop:      docker compose -f ${INSTALL_DIR}/docker-compose.yml down"
echo "================================================================"
