"""HMS Networks device templates."""

from app.services.device_templates._types import DeviceTemplate, FirmwareVariant, InstanceGenerationRules

from datetime import date


TEMPLATES: list[DeviceTemplate] = [
    DeviceTemplate(
        id="hms/anybus/xgateway",
        vendor="HMS",
        vendor_family="Anybus",
        model="Anybus X-gateway",
        model_name="Anybus X-gateway Protocol Converter",
        device_type="gateway",
        description="Multi-protocol industrial gateway",

        oui_prefixes=["00:30:11"],

        tcp_stack={
            "ttl": 64,
            "window_size": 16384,
            "mss": 1460,
            "sack_permitted": True,
            "timestamps_enabled": False,
        },

        response_timing={
            "min_ms": 2.0,
            "max_ms": 30.0,
            "mean_ms": 8.0,
            "std_dev_ms": 5.0,
            "distribution": "gaussian",
        },

        supported_protocols=["modbus_tcp", "ethernet_ip", "profinet"],

        modbus_identity={
            "vendor_name": "HMS Industrial Networks",
            "product_code": "AB7634",
            "major_minor_revision": "2.30",
            "vendor_url": "http://www.anybus.com",
            "product_name": "Anybus X-gateway Modbus TCP",
            "model_name": "Protocol Gateway",
        },

        ethernet_ip_identity={
            "vendor_id": 283,
            "device_type": 12,
            "product_code": 7634,
            "revision_major": 2,
            "revision_minor": 30,
            "serial_number": 0x484D5301,
            "product_name": "Anybus X-gateway EtherNet/IP",
            "state": 3,
        },

        profinet_identity={
            "vendor_id": 0x0128,
            "device_id": 0x0100,
            "device_type": "Anybus X-gateway PROFINET",
            "station_name": "anybus-xgw",
            "device_role": 1,
            "im0_manufacturer": "HMS Industrial Networks",
            "im0_order_id": "AB7634",
            "im0_hw_revision": 1,
            "im0_sw_revision": "V2.30",
        },

        instance_rules=InstanceGenerationRules(
            serial_format="HMS-{6HEX}",
            station_name_pattern="gw-proto-{seq}",
            vendor_short="HMS",
            model_short="ABXG",
        ),

        firmware_variants=[
            FirmwareVariant(
                version="2.30",
                release_date=date(2023, 6, 1),
                is_latest=True,
                is_default=True,
                cves=[],
            ),
        ],
    ),
    DeviceTemplate(
        id="hms/anybus/anybus-communicator",
        vendor="HMS",
        vendor_family="Anybus",
        model="Anybus Communicator",
        model_name="Anybus Communicator",
        device_type="gateway",
        description="HMS Anybus Communicator",
        oui_prefixes=['00:30:11'],
        tcp_stack={
                "ttl": 64,
                "window_size": 8192,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": False,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 40.0,
                "mean_ms": 12.0,
                "std_dev_ms": 7.0,
                "distribution": "gaussian",
                "outlier_probability": 0.004,
                "outlier_multiplier": 3.0,
            },
        error_behavior={
                "supported_exception_codes": [1, 2, 3],
                "exception_probability": 0.0005,
                "timeout_probability": 0.00025,
            },
        supported_protocols=['modbus', 'ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="1.50",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "HMS Industrial Networks",
                "product_code": "AB7072",
                "major_minor_revision": "1.50",
                "vendor_url": "http://www.anybus.com",
                "product_name": "Anybus Communicator EtherNet/IP",
                "model_name": "Serial-to-EtherNet Gateway",
            },
        ethernet_ip_identity={
                "vendor_id": 283,
                "device_type": 12,
                "product_code": 7072,
                "revision_major": 1,
                "revision_minor": 50,
                "serial_number": 1213027074,
                "product_name": "Anybus Communicator",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="hms/ewon/cosy-131",
        vendor="HMS",
        vendor_family="EWON",
        model="Cosy 131",
        model_name="Cosy 131",
        device_type="remote_access",
        description="HMS Cosy 131",
        oui_prefixes=['00:30:11'],
        tcp_stack={
                "ttl": 64,
                "window_size": 16384,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": False,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 50.0,
                "mean_ms": 15.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
                "outlier_probability": 0.004,
                "outlier_multiplier": 3.0,
            },
        error_behavior={
                "supported_exception_codes": [1, 2, 3, 4],
                "exception_probability": 0.0004,
                "timeout_probability": 0.0002,
            },
        supported_protocols=['modbus', 'ethernet_ip', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="14.8s0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "HMS Industrial Networks - EWON",
                "product_code": "EC131",
                "major_minor_revision": "14.8",
                "vendor_url": "https://www.ewon.biz",
                "product_name": "EWON Cosy 131 Remote Access Router",
                "model_name": "Remote Access Router",
            },
        ethernet_ip_identity={
                "vendor_id": 283,
                "device_type": 12,
                "product_code": 131,
                "revision_major": 14,
                "revision_minor": 8,
                "serial_number": 3960672257,
                "product_name": "EWON Cosy 131 Remote Access Router",
                "state": 3,
            },
        snmp_identity={
                "sys_descr": "EWON Cosy 131 Remote Access Router v14.8s0",
                "sys_object_id": "1.3.6.1.4.1.8284.2.2",
                "sys_name": "EWON-COSY-001",
                "sys_location": "Control Room",
            },
    ),
    DeviceTemplate(
        id="hms/ewon/flexy-205",
        vendor="HMS",
        vendor_family="EWON",
        model="Flexy 205",
        model_name="Flexy 205",
        device_type="remote_access",
        description="HMS Flexy 205",
        oui_prefixes=['00:30:11'],
        tcp_stack={
                "ttl": 64,
                "window_size": 32768,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 40.0,
                "mean_ms": 10.0,
                "std_dev_ms": 6.0,
                "distribution": "gaussian",
                "outlier_probability": 0.003,
                "outlier_multiplier": 3.5,
            },
        error_behavior={
                "supported_exception_codes": [1, 2, 3, 4],
                "exception_probability": 0.0003,
                "timeout_probability": 0.0001,
            },
        supported_protocols=['modbus', 'ethernet_ip', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="14.8s0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "HMS Industrial Networks - EWON",
                "product_code": "EF205",
                "major_minor_revision": "14.8",
                "vendor_url": "https://www.ewon.biz",
                "product_name": "EWON Flexy 205 Industrial IoT Gateway",
                "model_name": "Remote Access Gateway",
            },
        ethernet_ip_identity={
                "vendor_id": 283,
                "device_type": 12,
                "product_code": 205,
                "revision_major": 14,
                "revision_minor": 8,
                "serial_number": 1163349505,
                "product_name": "EWON Flexy 205",
                "state": 3,
            },
        snmp_identity={
                "sys_descr": "EWON Flexy 205 Industrial IoT Gateway v14.8s0",
                "sys_object_id": "1.3.6.1.4.1.8284.2.1",
                "sys_name": "EWON-FLEXY-001",
                "sys_location": "Industrial DMZ",
            },
    ),
    DeviceTemplate(
        id="hms/ewon-flexy/flexy-205",
        vendor="HMS",
        vendor_family="eWON Flexy",
        model="Flexy 205",
        model_name="Flexy 205",
        device_type="remote_access",
        description="HMS Flexy 205",
        oui_prefixes=['00:06:71'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 100.0,
                "mean_ms": 25.0,
                "std_dev_ms": 20.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="14.5",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "HMS Industrial Networks",
                "product_code": "Flexy205",
                "major_minor_revision": "14.5",
                "product_name": "eWON Flexy 205 Industrial Router",
                "model_name": "Flexy205",
            },
        snmp_identity={
                "sys_descr": "eWON Flexy 205 - Firmware 14.5s0",
                "sys_object_id": "1.3.6.1.4.1.8284.2.1",
                "sys_name": "FLEXY-205-001",
                "sys_location": "Remote Site",
                "sys_contact": "remote@facility.local",
            },
    ),
]
