# PacketArch — OT Traffic Simulation Platform
# Copyright (c) 2026 Rocky Smith <rocky.d.smith@proton.me>
# Licensed under GPL-3.0. See LICENSE at the repo root.
"""IT/OT boundary device templates (Microsoft, Bosch)."""

from app.services.device_templates._types import DeviceTemplate, FirmwareVariant

from datetime import date


TEMPLATES: list[DeviceTemplate] = [
    DeviceTemplate(
        id="bosch/ptz-camera/mic-ip-7100i",
        vendor="Bosch",
        vendor_family="PTZ Camera",
        model="MIC IP 7100i",
        model_name="MIC IP 7100i",
        device_type="camera",
        description="Bosch MIC IP 7100i",
        oui_prefixes=['00:04:13', '00:07:5F'],
        tcp_stack={
                "ttl": 64,
                "window_size": 32768,
                "mss": 1460,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 25.0,
                "mean_ms": 8.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
                "outlier_probability": 0.01,
                "outlier_multiplier": 3.0,
            },
        error_behavior={
                "timeout_probability": 0.001,
                "retry_behavior": True,
                "max_retries": 3,
            },
        supported_protocols=['snmp', 'ssh', 'telnet', 'rdp', 'https'],
        firmware_variants=[FirmwareVariant(
            version="7.82.0127",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Bosch MIC IP 7100i PTZ Camera 7.82.0127",
                "sys_object_id": "1.3.6.1.4.1.3246.1.1.7100",
                "sys_name": "CAM-BOSCH-001",
                "ntcip_device_type": "camera",
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2008-r2-vulnerable",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2008 R2 (Vulnerable)",
        model_name="Jump Server 2008 R2 (Vulnerable)",
        device_type="server",
        description="Microsoft Jump Server 2008 R2 (Vulnerable)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": False,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 50.0,
                "mean_ms": 18.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'ssh', 'telnet', 'rdp', 'https'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                },
                "smb": {
                    "v1_enabled": True,
                    "signing_required": False,
                },
            },
        firmware_variants=[FirmwareVariant(
            version="6.1.7601",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.1 (Build 7601 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - Legacy OT Access",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2016-vulnerable",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2016 (Vulnerable)",
        model_name="Jump Server 2016 (Vulnerable)",
        device_type="server",
        description="Microsoft Jump Server 2016 (Vulnerable)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
            },
        # Jump server is a Windows admin host. It speaks IT mgmt protocols
        # natively (SSH/RDP/SNMP/HTTPS); modbus_tcp/opc_ua belong to
        # post-pivot ad-hoc tooling and should not appear in the device's
        # native fingerprint — that pollutes flow-protocol snapping.
        supported_protocols=['snmp', 'ssh', 'telnet', 'rdp', 'https'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                },
                "rdp": {
                    "nla_enabled": False,
                    "port": 3389,
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.14393",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 14393 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - OT Access",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2019",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2019",
        model_name="Jump Server 2019",
        device_type="server",
        description="Microsoft Jump Server 2019",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 25.0,
                "mean_ms": 8.0,
                "std_dev_ms": 2.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'ssh', 'telnet', 'rdp', 'https'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [('1.3.6.1.4.1.311.1.1.3.1.1', 'Windows NT'), ('1.3.6.1.4.1.311.1.1.3.1.2', 'Microsoft Corporation')],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.17763.5458",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 17763 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - OT Access",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/wsus-server-2019",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="WSUS Server 2019",
        model_name="WSUS Server 2019",
        device_type="server",
        description="Microsoft Windows Server Update Services 2019 (WSUS)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'smb', 'rdp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.311.1.1.3.1.5', 'Windows Server Update Services'),
                        ('1.3.6.1.4.1.311.1.1.3.1.2', 'Microsoft Corporation'),
                    ],
                },
                "https": {
                    "port": 8531,
                    "server_header": "Microsoft-HTTPAPI/2.0",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.17763.6189",
            release_date=date(2024, 7, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 17763 Multiprocessor Free) - Role: WSUS",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.5",
                "sys_name": "{device_name}",
                "sys_contact": "wsus-admin@example.com",
                "sys_location": "IDMZ - Patch Staging",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/wsus-server-2022",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="WSUS Server 2022",
        model_name="WSUS Server 2022",
        device_type="server",
        description="Microsoft Windows Server Update Services 2022 (WSUS)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 25.0,
                "mean_ms": 8.0,
                "std_dev_ms": 2.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'smb', 'rdp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.311.1.1.3.1.5', 'Windows Server Update Services'),
                        ('1.3.6.1.4.1.311.1.1.3.1.2', 'Microsoft Corporation'),
                    ],
                },
                "https": {
                    "port": 8531,
                    "server_header": "Microsoft-HTTPAPI/2.0",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.20348.2700",
            release_date=date(2024, 8, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 106 Stepping 6 AT/AT COMPATIBLE - Software: Windows Version 10.0 (Build 20348 Multiprocessor Free) - Role: WSUS",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.5",
                "sys_name": "{device_name}",
                "sys_contact": "wsus-admin@example.com",
                "sys_location": "IDMZ - Patch Staging",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/sccm-mecm-2022",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="MECM Server 2022",
        model_name="MECM Server 2022",
        device_type="server",
        description="Microsoft Endpoint Configuration Manager (SCCM / MECM)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 40.0,
                "mean_ms": 14.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'smb', 'rdp', 'mssql'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.311.1.1.3.1.6', 'Microsoft Endpoint Configuration Manager'),
                        ('1.3.6.1.4.1.311.1.1.3.1.2', 'Microsoft Corporation'),
                    ],
                },
                "https": {
                    "port": 443,
                    "server_header": "Microsoft-IIS/10.0",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="5.0.9128.1000",
            release_date=date(2024, 4, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 106 Stepping 6 AT/AT COMPATIBLE - Software: Windows Version 10.0 (Build 20348 Multiprocessor Free) - Role: MECM",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.6",
                "sys_name": "{device_name}",
                "sys_contact": "mecm-admin@example.com",
                "sys_location": "IDMZ - Endpoint Management",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/defender-for-endpoint-2022",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Defender for Endpoint 2022",
        model_name="Defender for Endpoint 2022",
        device_type="server",
        description="Microsoft Defender for Endpoint management server",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 30.0,
                "mean_ms": 9.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'smb', 'rdp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.311.1.1.3.1.7', 'Microsoft Defender for Endpoint'),
                        ('1.3.6.1.4.1.311.1.1.3.1.2', 'Microsoft Corporation'),
                    ],
                },
                "https": {
                    "port": 443,
                    "server_header": "Microsoft-IIS/10.0",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.8210.22621.4112",
            release_date=date(2024, 9, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 106 Stepping 6 AT/AT COMPATIBLE - Software: Windows Version 10.0 (Build 20348 Multiprocessor Free) - Role: Defender",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.7",
                "sys_name": "{device_name}",
                "sys_contact": "secops@example.com",
                "sys_location": "IDMZ - Endpoint Security",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="broadcom/symantec/sepm-14",
        vendor="Broadcom",
        vendor_family="Symantec",
        model="Symantec Endpoint Protection Manager 14",
        model_name="Symantec Endpoint Protection Manager 14",
        device_type="server",
        description="Broadcom Symantec Endpoint Protection Manager (SEPM)",
        oui_prefixes=['00:1B:21', '00:50:56', '00:0C:29'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 11.0,
                "std_dev_ms": 3.5,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'smb'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.393.5.1.1', 'Symantec Endpoint Protection Manager'),
                    ],
                },
                "https": {
                    "port": 8446,
                    "server_header": "Apache-Coyote/1.1",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="14.3.10000.7000",
            release_date=date(2024, 2, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Symantec Endpoint Protection Manager 14.3 RU7 - Build 10000",
                "sys_object_id": "1.3.6.1.4.1.393.5.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "secops@example.com",
                "sys_location": "IDMZ - Endpoint Security",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="paessler/network-monitor/prtg-24",
        vendor="Paessler",
        vendor_family="Network Monitor",
        model="PRTG Network Monitor 24",
        model_name="PRTG Network Monitor 24",
        device_type="server",
        description="Paessler PRTG Network Monitor — NMS appliance",
        oui_prefixes=['00:15:5D', '00:50:56', '00:0C:29'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 30.0,
                "mean_ms": 9.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'icmp', 'wmi'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.32446.1.1.1', 'PRTG Network Monitor'),
                    ],
                },
                "https": {
                    "port": 443,
                    "server_header": "PRTG/24.4.97.1865",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="24.4.97.1865",
            release_date=date(2024, 10, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Paessler PRTG Network Monitor 24.4 - Windows Server backend",
                "sys_object_id": "1.3.6.1.4.1.32446.1.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "netops@example.com",
                "sys_location": "Plant Operations - NMS",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="aveva/pi-system/pi-server-2018",
        vendor="Aveva",
        vendor_family="PI System",
        model="OSIsoft PI Server 2018",
        model_name="OSIsoft PI Server 2018",
        device_type="server",
        description="Aveva / OSIsoft PI Server (data archive + AF)",
        oui_prefixes=['00:15:5D', '00:50:56', '00:0C:29'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 40.0,
                "mean_ms": 13.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'opc_ua', 'pi'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.9810.1.1', 'OSIsoft PI Server'),
                    ],
                },
                "pi": {
                    "port": 5450,
                    "server_header": "PI Data Archive 2018 SP3 Patch 4",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="3.4.445.688",
            release_date=date(2023, 7, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Aveva PI Server 2018 SP3 Patch 4 - Data Archive + Asset Framework",
                "sys_object_id": "1.3.6.1.4.1.9810.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "pi-admin@example.com",
                "sys_location": "Plant Operations - Batch / PI",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "OSIsoft PI OPC UA Server",
                "application_uri": "urn:OSIsoft:PI:UAServer",
                "product_uri": "https://www.osisoft.com/pi-server",
                "manufacturer_name": "AVEVA / OSIsoft",
                "product_name": "PI Server OPC UA Server",
                "software_version": "3.4.445.688",
                "build_number": "2018 SP3 Patch 4",
            },
    ),
    DeviceTemplate(
        id="siemens/opcenter/execution-discrete-2406",
        vendor="Siemens",
        vendor_family="Opcenter",
        model="Opcenter Execution Discrete 2406",
        model_name="Opcenter Execution Discrete 2406",
        device_type="server",
        description="Siemens Opcenter Execution Discrete (MES)",
        oui_prefixes=['00:1B:1B', '00:0E:8C', '00:1F:F8', '00:15:5D', '00:50:56'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 45.0,
                "mean_ms": 15.0,
                "std_dev_ms": 5.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'opc_ua', 'mssql'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.4329.50.1.1', 'Siemens Opcenter Execution Discrete'),
                    ],
                },
                "https": {
                    "port": 443,
                    "server_header": "Microsoft-IIS/10.0",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="24.6.1.0",
            release_date=date(2024, 6, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Siemens Opcenter Execution Discrete 24.6 - MES platform",
                "sys_object_id": "1.3.6.1.4.1.4329.50.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "mes-admin@example.com",
                "sys_location": "Plant Operations - MES",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "Siemens Opcenter Execution Discrete OPC UA Server",
                "application_uri": "urn:Siemens:Opcenter:Execution:UAServer",
                "product_uri": "https://www.siemens.com/opcenter",
                "manufacturer_name": "Siemens AG",
                "product_name": "Opcenter Execution Discrete OPC UA Server",
                "software_version": "24.6.1.0",
                "build_number": "24.6",
            },
    ),
    DeviceTemplate(
        id="lansweeper/it-asset-mgmt/lansweeper-11",
        vendor="Lansweeper",
        vendor_family="IT Asset Management",
        model="Lansweeper 11",
        model_name="Lansweeper 11",
        device_type="server",
        description="Lansweeper IT asset discovery + inventory server",
        oui_prefixes=['00:15:5D', '00:50:56', '00:0C:29'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 11.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'wmi', 'mssql'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.55001.1.1', 'Lansweeper Asset Discovery'),
                    ],
                },
                "https": {
                    "port": 443,
                    "server_header": "Kestrel",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="11.5.20",
            release_date=date(2024, 7, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Lansweeper 11.5 - IT Asset Discovery + Inventory",
                "sys_object_id": "1.3.6.1.4.1.55001.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "itam@example.com",
                "sys_location": "Plant Operations - Asset Mgmt",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="aveva/intouch/alarm-server-2023",
        vendor="Aveva",
        vendor_family="InTouch",
        model="InTouch Alarm Server 2023",
        model_name="InTouch Alarm Server 2023",
        device_type="server",
        description="Aveva InTouch Alarm + Event Server",
        oui_prefixes=['00:15:5D', '00:50:56', '00:0C:29'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 11.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'opc_ua', 'mssql'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.18763.1.1', 'Aveva InTouch Alarm Server'),
                    ],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="2023 R2 (23.2.0)",
            release_date=date(2024, 3, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Aveva InTouch Alarm + Event Server 2023 R2",
                "sys_object_id": "1.3.6.1.4.1.18763.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "controls@example.com",
                "sys_location": "Plant Operations - Alarm Server",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "AVEVA InTouch Alarm Server OPC UA Server",
                "application_uri": "urn:AVEVA:InTouch:AlarmServer:UAServer",
                "product_uri": "https://www.aveva.com/intouch",
                "manufacturer_name": "AVEVA",
                "product_name": "InTouch Alarm + Event Server OPC UA Server",
                "software_version": "23.2.0",
                "build_number": "2023 R2",
            },
    ),
    DeviceTemplate(
        id="f5/big-ip/ltm-i2800",
        vendor="F5 Networks",
        vendor_family="BIG-IP",
        model="BIG-IP i2800",
        model_name="BIG-IP i2800",
        device_type="appliance",
        description="F5 BIG-IP LTM reverse proxy / load balancer",
        oui_prefixes=['00:01:D7', '00:94:A1', 'F4:0F:24'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 1.0,
                "max_ms": 12.0,
                "mean_ms": 4.0,
                "std_dev_ms": 1.5,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'ssh'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.3375.2.1.1', 'F5 BIG-IP LTM'),
                    ],
                },
                "https": {
                    "port": 443,
                    "server_header": "BIG-IP",
                },
            },
        firmware_variants=[FirmwareVariant(
            version="17.1.1.4",
            release_date=date(2024, 5, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "BIG-IP 17.1.1 Build 0.0.20 Final on F5 i2800 Platform",
                "sys_object_id": "1.3.6.1.4.1.3375.2.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "netops@example.com",
                "sys_location": "IDMZ - Reverse Proxy",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="rockwell/factorytalk/view-se-station-14",
        vendor="Rockwell",
        vendor_family="FactoryTalk",
        model="FactoryTalk View SE Station 14",
        model_name="FactoryTalk View SE Station 14",
        device_type="server",
        description="Rockwell FactoryTalk View SE Station (HMI/SCADA on Windows)",
        oui_prefixes=['00:00:BC', '00:1D:9C', '00:50:56'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'ethernet_ip', 'https', 'http', 'opc_ua'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.7790.50.1', 'Rockwell FactoryTalk View SE'),
                    ],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="14.00.00 (CPR 9 SR 14)",
            release_date=date(2024, 6, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Rockwell FactoryTalk View SE Station 14.00 (CPR 9 SR 14)",
                "sys_object_id": "1.3.6.1.4.1.7790.50.1",
                "sys_name": "{device_name}",
                "sys_contact": "controls@example.com",
                "sys_location": "Plant Operations - SCADA",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "Rockwell FactoryTalk View SE OPC UA Client",
                "application_uri": "urn:Rockwell:FactoryTalk:ViewSE:UAClient",
                "product_uri": "https://www.rockwellautomation.com/factorytalk-view-se",
                "manufacturer_name": "Rockwell Automation",
                "product_name": "FactoryTalk View SE Station OPC UA Client",
                "software_version": "14.00.00",
                "build_number": "CPR 9 SR 14",
            },
        # Client-side identity — FactoryTalk View SE originates EtherNet/IP
        # sessions to ControlLogix endpoints; CV sees the client identity
        # tag in the CIP forwardOpen exchange.
        ethernet_ip_identity={
                "vendor_id": 1,  # Rockwell
                "device_type": 12,  # Communications Adapter
                "product_code": 5014,
                "product_name": "FactoryTalk View SE EtherNet/IP Client",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="rockwell/studio-5000/logix-designer-36",
        vendor="Rockwell",
        vendor_family="Studio 5000",
        model="Studio 5000 Logix Designer 36",
        model_name="Studio 5000 Logix Designer 36",
        device_type="server",
        description="Rockwell Studio 5000 Logix Designer (engineering workstation)",
        oui_prefixes=['00:00:BC', '00:1D:9C', '00:50:56'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'ethernet_ip', 'https', 'http'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.7790.50.2', 'Rockwell Studio 5000 Logix Designer'),
                    ],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="36.00.00",
            release_date=date(2024, 4, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Rockwell Studio 5000 Logix Designer 36.00 - Engineering Workstation",
                "sys_object_id": "1.3.6.1.4.1.7790.50.2",
                "sys_name": "{device_name}",
                "sys_contact": "engineering@example.com",
                "sys_location": "Plant Operations - Engineering",
                "sys_services": 76,
            },
        ethernet_ip_identity={
                "vendor_id": 1,
                "device_type": 12,  # Communications Adapter (engineering tool)
                "product_code": 5036,
                "product_name": "Studio 5000 Logix Designer EtherNet/IP Client",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="schneider/ecostruxure/control-expert-16",
        vendor="Schneider",
        vendor_family="EcoStruxure",
        model="EcoStruxure Control Expert 16",
        model_name="EcoStruxure Control Expert 16",
        device_type="server",
        description="Schneider EcoStruxure Control Expert (PLC engineering on Windows)",
        oui_prefixes=['00:80:F4', '00:80:6F', '00:50:56'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'modbus_tcp', 'https', 'http', 'opc_ua'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.3833.1.10.1', 'Schneider EcoStruxure Control Expert'),
                    ],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="16.0",
            release_date=date(2024, 5, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Schneider EcoStruxure Control Expert 16.0 - PLC Programming",
                "sys_object_id": "1.3.6.1.4.1.3833.1.10.1",
                "sys_name": "{device_name}",
                "sys_contact": "engineering@example.com",
                "sys_location": "Plant Operations - Engineering",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "Schneider EcoStruxure Control Expert OPC UA Client",
                "application_uri": "urn:SchneiderElectric:EcoStruxure:ControlExpert:UAClient",
                "product_uri": "https://www.se.com/ww/en/product-range/548-ecostruxure-control-expert/",
                "manufacturer_name": "Schneider Electric",
                "product_name": "EcoStruxure Control Expert OPC UA Client",
                "software_version": "16.0",
                "build_number": "V16.0",
            },
        modbus_identity={
                "vendor_name": "Schneider Electric",
                "product_code": "EcoStruxure Control Expert 16.0",
                "product_name": "EcoStruxure Control Expert Modbus TCP Client",
                "model_name": "EcoStruxure Control Expert",
            },
    ),
    DeviceTemplate(
        id="schneider/geo-scada/expert-2022",
        vendor="Schneider",
        vendor_family="Geo SCADA",
        model="Geo SCADA Expert 2022",
        model_name="Geo SCADA Expert 2022",
        device_type="server",
        description="Schneider Geo SCADA Expert (SCADA on Windows)",
        oui_prefixes=['00:80:F4', '00:80:6F', '00:50:56'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'opc_ua', 'modbus_tcp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.3833.1.20.1', 'Schneider Geo SCADA Expert'),
                    ],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="2022 R2 (84.10847)",
            release_date=date(2024, 3, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Schneider Geo SCADA Expert 2022 R2 (84.10847) - SCADA",
                "sys_object_id": "1.3.6.1.4.1.3833.1.20.1",
                "sys_name": "{device_name}",
                "sys_contact": "controls@example.com",
                "sys_location": "Plant Operations - SCADA",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "Schneider Geo SCADA Expert OPC UA Server",
                "application_uri": "urn:SchneiderElectric:GeoSCADA:Expert:UAServer",
                "product_uri": "https://www.se.com/ww/en/product-range/61264-ecostruxure-geo-scada-expert/",
                "manufacturer_name": "Schneider Electric",
                "product_name": "Geo SCADA Expert OPC UA Server",
                "software_version": "84.10847",
                "build_number": "2022 R2",
            },
        modbus_identity={
                "vendor_name": "Schneider Electric",
                "product_code": "Geo SCADA Expert 2022 R2",
                "product_name": "Geo SCADA Expert Modbus TCP Client",
                "model_name": "Geo SCADA Expert",
            },
    ),
    DeviceTemplate(
        id="abb/800xa/operator-workplace-611",
        vendor="ABB",
        vendor_family="800xA",
        model="800xA Operator Workplace 6.1.1",
        model_name="800xA Operator Workplace 6.1.1",
        device_type="server",
        description="ABB 800xA Operator Workplace (DCS HMI on Windows)",
        oui_prefixes=['00:1B:1B', '00:1F:F8', '00:50:56'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 13.0,
                "std_dev_ms": 3.5,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'https', 'http', 'opc_ua'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [
                        ('1.3.6.1.4.1.5677.1.1.1', 'ABB 800xA Operator Workplace'),
                    ],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="6.1.1-1",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "ABB 800xA Operator Workplace 6.1.1-1 - DCS HMI",
                "sys_object_id": "1.3.6.1.4.1.5677.1.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "controls@example.com",
                "sys_location": "Plant Operations - DCS",
                "sys_services": 76,
            },
        opc_ua_identity={
                "application_name": "ABB 800xA Operator Workplace OPC UA Client",
                "application_uri": "urn:ABB:800xA:OperatorWorkplace:UAClient",
                "product_uri": "https://new.abb.com/control-systems/system-800xa",
                "manufacturer_name": "ABB",
                "product_name": "800xA Operator Workplace OPC UA Client",
                "software_version": "6.1.1-1",
                "build_number": "V6.1.1",
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2019-printnightmare",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2019 (PrintNightmare)",
        model_name="Jump Server 2019 (PrintNightmare)",
        device_type="server",
        description="Microsoft Jump Server 2019 (PrintNightmare)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 30.0,
                "mean_ms": 10.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp', 'ssh', 'telnet', 'rdp', 'https'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                },
                "print_spooler": {
                    "enabled": True,
                    "remote_access": True,
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.17763.1",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 17763 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - OT Access",
                "sys_services": 76,
            },
    ),
]
