# PacketArch — OT Traffic Simulation Platform
# Copyright (c) 2026 Rocky Smith <rocky.d.smith@proton.me>
# Licensed under GPL-3.0. See LICENSE at the repo root.
"""IT/OT boundary device templates (Microsoft, Bosch)."""

from app.services.device_templates._types import DeviceTemplate, FirmwareVariant

from datetime import date


TEMPLATES: list[DeviceTemplate] = [
    DeviceTemplate(
        id="bosch/ptz-camera/mic-ip-7100i",
        vendor="Bosch",
        vendor_family="PTZ Camera",
        model="MIC IP 7100i",
        model_name="MIC IP 7100i",
        device_type="camera",
        description="Bosch MIC IP 7100i",
        oui_prefixes=['00:04:13', '00:07:5F'],
        tcp_stack={
                "ttl": 64,
                "window_size": 32768,
                "mss": 1460,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 25.0,
                "mean_ms": 8.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
                "outlier_probability": 0.01,
                "outlier_multiplier": 3.0,
            },
        error_behavior={
                "timeout_probability": 0.001,
                "retry_behavior": True,
                "max_retries": 3,
            },
        supported_protocols=['snmp'],
        firmware_variants=[FirmwareVariant(
            version="7.82.0127",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Bosch MIC IP 7100i PTZ Camera 7.82.0127",
                "sys_object_id": "1.3.6.1.4.1.3246.1.1.7100",
                "sys_name": "CAM-BOSCH-001",
                "ntcip_device_type": "camera",
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2008-r2-vulnerable",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2008 R2 (Vulnerable)",
        model_name="Jump Server 2008 R2 (Vulnerable)",
        device_type="server",
        description="Microsoft Jump Server 2008 R2 (Vulnerable)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": False,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 50.0,
                "mean_ms": 18.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                },
                "smb": {
                    "v1_enabled": True,
                    "signing_required": False,
                },
            },
        firmware_variants=[FirmwareVariant(
            version="6.1.7601",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.1 (Build 7601 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - Legacy OT Access",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2016-vulnerable",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2016 (Vulnerable)",
        model_name="Jump Server 2016 (Vulnerable)",
        device_type="server",
        description="Microsoft Jump Server 2016 (Vulnerable)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 35.0,
                "mean_ms": 12.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                },
                "rdp": {
                    "nla_enabled": False,
                    "port": 3389,
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.14393",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 14393 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - OT Access",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2019",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2019",
        model_name="Jump Server 2019",
        device_type="server",
        description="Microsoft Jump Server 2019",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 25.0,
                "mean_ms": 8.0,
                "std_dev_ms": 2.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                    "additional_oids": [('1.3.6.1.4.1.311.1.1.3.1.1', 'Windows NT'), ('1.3.6.1.4.1.311.1.1.3.1.2', 'Microsoft Corporation')],
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.17763.5458",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 17763 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - OT Access",
                "sys_services": 76,
            },
    ),
    DeviceTemplate(
        id="microsoft/windows-server/jump-server-2019-printnightmare",
        vendor="Microsoft",
        vendor_family="Windows Server",
        model="Jump Server 2019 (PrintNightmare)",
        model_name="Jump Server 2019 (PrintNightmare)",
        device_type="server",
        description="Microsoft Jump Server 2019 (PrintNightmare)",
        oui_prefixes=['00:15:5D', '00:1D:D8', '00:50:F2', '00:03:FF', '7C:1E:52'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 30.0,
                "mean_ms": 10.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['snmp'],
        protocol_quirks={
                "snmp": {
                    "community_string": "public",
                    "version": "2c",
                },
                "print_spooler": {
                    "enabled": True,
                    "remote_access": True,
                },
            },
        firmware_variants=[FirmwareVariant(
            version="10.0.17763.1",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        snmp_identity={
                "sys_descr": "Hardware: Intel64 Family 6 Model 85 Stepping 7 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 17763 Multiprocessor Free)",
                "sys_object_id": "1.3.6.1.4.1.311.1.1.3.1.1",
                "sys_name": "{device_name}",
                "sys_contact": "admin@example.com",
                "sys_location": "Server Room - OT Access",
                "sys_services": 76,
            },
    ),
]
