"""Robotics and logistics device templates (KUKA, Fanuc, MiR, Dematic, Cognex, Impinj, Zebra)."""

from app.services.device_templates._types import DeviceTemplate, FirmwareVariant, InstanceGenerationRules

from datetime import date


TEMPLATES: list[DeviceTemplate] = [
    DeviceTemplate(
        id="fanuc/robot/r30ib-plus",
        vendor="Fanuc",
        vendor_family="Robot Controller",
        model="R-30iB Plus",
        model_name="R-30iB Plus Robot Controller",
        device_type="robot_controller",
        description="Latest generation robot controller with integrated motion control",

        oui_prefixes=["00:E0:E4", "00:E0:E5"],

        tcp_stack={
            "ttl": 128,  # Windows CE based
            "window_size": 65535,
            "mss": 1460,
            "sack_permitted": True,
            "timestamps_enabled": True,
            "window_scaling": 8,
        },

        response_timing={
            "min_ms": 0.5,
            "max_ms": 20.0,
            "mean_ms": 4.0,
            "std_dev_ms": 3.0,
            "distribution": "gaussian",
        },

        supported_protocols=["fanuc", "ethernet_ip"],

        instance_rules=InstanceGenerationRules(
            serial_format="R30-{8HEX}",
            station_name_pattern="robot-{seq}",
            vendor_short="FAN",
            model_short="R30",
        ),

        firmware_variants=[
            FirmwareVariant(
                version="V9.40",
                release_date=date(2024, 2, 1),
                is_latest=True,
                is_default=True,
                cves=[],
            ),
            FirmwareVariant(
                version="V9.30",
                release_date=date(2023, 5, 15),
                cves=["CVE-2023-24523"],
            ),
            FirmwareVariant(
                version="V9.10",
                release_date=date(2021, 9, 20),
                cves=["CVE-2023-24523", "CVE-2021-38296"],
            ),
        ],

        ethernet_ip_identity={
            "vendor_id": 27,  # Fanuc
            "device_type": 21,  # Robot
            "product_code": 30,
            "state": 3,
        },
    ),
    DeviceTemplate(
        id="fanuc/cnc/0i-tf-plus",
        vendor="Fanuc",
        vendor_family="CNC",
        model="0i-TF Plus",
        model_name="Series 0i-TF Plus CNC",
        device_type="cnc_controller",
        description="High-performance CNC controller for turning and milling",

        oui_prefixes=["00:E0:E4", "00:E0:E5"],

        tcp_stack={
            "ttl": 128,
            "window_size": 65535,
            "mss": 1460,
            "sack_permitted": True,
            "timestamps_enabled": True,
        },

        response_timing={
            "min_ms": 0.3,
            "max_ms": 12.0,
            "mean_ms": 2.5,
            "std_dev_ms": 1.5,
            "distribution": "gaussian",
        },

        supported_protocols=["fanuc", "modbus_tcp"],

        instance_rules=InstanceGenerationRules(
            serial_format="CNC-{10NUM}",
            station_name_pattern="cnc-{location}-{seq}",
            vendor_short="FAN",
            model_short="0iTF",
        ),

        firmware_variants=[
            FirmwareVariant(
                version="V34.2",
                release_date=date(2024, 1, 20),
                is_latest=True,
                is_default=True,
                cves=[],
            ),
            FirmwareVariant(
                version="V33.0",
                release_date=date(2022, 7, 10),
                cves=["CVE-2023-24523"],
            ),
        ],

        modbus_identity={
            "vendor_name": "Fanuc Corporation",
            "product_code": "0i-TF Plus",
            "product_name": "Series 0i-TF Plus CNC",
        },
    ),
    DeviceTemplate(
        id="kuka/robot/krc4",
        vendor="KUKA",
        vendor_family="KR C",
        model="KR C4",
        model_name="KR C4 Robot Controller",
        device_type="robot_controller",
        description="8th generation robot controller for KUKA industrial robots",

        oui_prefixes=["00:1A:28", "00:1F:29"],

        tcp_stack={
            "ttl": 128,  # Windows based
            "window_size": 65535,
            "mss": 1460,
            "window_scaling": 8,
            "sack_permitted": True,
            "timestamps_enabled": True,
        },

        response_timing={
            "min_ms": 0.8,
            "max_ms": 25.0,
            "mean_ms": 5.0,
            "std_dev_ms": 3.5,
            "distribution": "gaussian",
        },

        supported_protocols=["ethernet_ip", "profinet"],

        instance_rules=InstanceGenerationRules(
            serial_format="KRC4-{8HEX}",
            station_name_pattern="robot-{location}-{seq}",
            vendor_short="KUK",
            model_short="KRC4",
        ),

        firmware_variants=[
            FirmwareVariant(
                version="V8.6.8",
                release_date=date(2024, 1, 30),
                is_latest=True,
                is_default=True,
                cves=[],
            ),
            FirmwareVariant(
                version="V8.5.10",
                release_date=date(2022, 8, 20),
                cves=["CVE-2022-43560"],
            ),
            FirmwareVariant(
                version="V8.3.5",
                release_date=date(2020, 11, 15),
                cves=["CVE-2022-43560", "CVE-2020-10292"],
            ),
        ],

        ethernet_ip_identity={
            "vendor_id": 270,  # KUKA
            "device_type": 21,  # Robot
            "product_code": 4,
            "state": 3,
        },

        profinet_identity={
            "vendor_id": 0x0115,  # KUKA
            "device_id": 0x0004,
            "device_role": 1,
            "im0_manufacturer": "KUKA Roboter GmbH",
            "im0_order_id": "KR C4",
        },
    ),
    DeviceTemplate(
        id="cognex/dataman/dataman-280",
        vendor="Cognex",
        vendor_family="DataMan",
        model="DataMan 280",
        model_name="DataMan 280",
        device_type="barcode_scanner",
        description="Cognex DataMan 280",
        oui_prefixes=['00:04:3E', '00:0D:88'],
        tcp_stack={
                "ttl": 64,
                "window_size": 16384,
                "mss": 1460,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 40.0,
                "mean_ms": 12.0,
                "std_dev_ms": 6.0,
                "distribution": "gaussian",
            },
        supported_protocols=['ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="6.1.5",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        ethernet_ip_identity={
                "vendor_id": 112,
                "device_type": 43,
                "product_code": 280,
                "revision_major": 6,
                "revision_minor": 1,
                "product_name": "DataMan 280 Barcode Reader",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="cognex/dataman/dataman-370",
        vendor="Cognex",
        vendor_family="DataMan",
        model="DataMan 370",
        model_name="DataMan 370",
        device_type="barcode_scanner",
        description="Cognex DataMan 370",
        oui_prefixes=['00:04:3E', '00:0D:88'],
        tcp_stack={
                "ttl": 64,
                "window_size": 16384,
                "mss": 1460,
                "sack_permitted": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 50.0,
                "mean_ms": 15.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="6.2.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Cognex Corporation",
                "product_code": "DataMan 370",
                "major_minor_revision": "6.2.0",
                "product_name": "DataMan 370 Fixed-Mount Barcode Reader",
                "model_name": "DataMan 370",
            },
        ethernet_ip_identity={
                "vendor_id": 112,
                "device_type": 43,
                "product_code": 370,
                "revision_major": 6,
                "revision_minor": 2,
                "product_name": "DataMan 370 Barcode Reader",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="cognex/in-sight/in-sight-7802",
        vendor="Cognex",
        vendor_family="In-Sight",
        model="In-Sight 7802",
        model_name="In-Sight 7802",
        device_type="vision_system",
        description="Cognex In-Sight 7802",
        oui_prefixes=['00:04:3E', '00:0D:88'],
        tcp_stack={
                "ttl": 64,
                "window_size": 32768,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": False,
            },
        response_timing={
                "min_ms": 10.0,
                "max_ms": 100.0,
                "mean_ms": 35.0,
                "std_dev_ms": 20.0,
                "distribution": "gaussian",
            },
        supported_protocols=['ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="6.3.2",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        ethernet_ip_identity={
                "vendor_id": 112,
                "device_type": 43,
                "product_code": 7802,
                "revision_major": 6,
                "revision_minor": 3,
                "serial_number": 1230190392,
                "product_name": "In-Sight 7802 Vision System",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="dematic/iq-platform/iq-wcs-controller",
        vendor="Dematic",
        vendor_family="iQ Platform",
        model="iQ WCS Controller",
        model_name="iQ WCS Controller",
        device_type="server",
        description="Dematic iQ WCS Controller",
        oui_prefixes=['00:1C:34'],
        tcp_stack={
                "ttl": 128,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 1.0,
                "max_ms": 20.0,
                "mean_ms": 5.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="5.4.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Dematic Corporation",
                "product_code": "iQ-WCS",
                "major_minor_revision": "5.4.0",
                "product_name": "Dematic iQ Warehouse Control System",
                "model_name": "iQ WCS",
            },
        ethernet_ip_identity={
                "vendor_id": 0,
                "device_type": 12,
                "product_code": 5400,
                "revision_major": 5,
                "revision_minor": 4,
                "product_name": "Dematic iQ WCS",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="impinj/speedway/speedway-r420",
        vendor="Impinj",
        vendor_family="Speedway",
        model="Speedway R420",
        model_name="Speedway R420",
        device_type="rfid_reader",
        description="Impinj Speedway R420",
        oui_prefixes=['00:16:25'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 40.0,
                "mean_ms": 15.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="7.5.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Impinj Inc",
                "product_code": "Speedway R420",
                "major_minor_revision": "7.5.0",
                "product_name": "Impinj Speedway R420 RAIN RFID Reader",
                "model_name": "R420",
            },
        snmp_identity={
                "sys_descr": "Impinj Speedway R420 RAIN RFID Reader V7.5.0",
                "sys_object_id": "1.3.6.1.4.1.25882.1.2",
                "sys_name": "SPEEDWAY-R420-001",
            },
    ),
    DeviceTemplate(
        id="impinj/speedway/speedway-r700",
        vendor="Impinj",
        vendor_family="Speedway",
        model="Speedway R700",
        model_name="Speedway R700",
        device_type="rfid_reader",
        description="Impinj Speedway R700",
        oui_prefixes=['00:16:25'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 3.0,
                "max_ms": 30.0,
                "mean_ms": 10.0,
                "std_dev_ms": 5.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="8.2.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Impinj Inc",
                "product_code": "Speedway R700",
                "major_minor_revision": "8.2.0",
                "vendor_url": "https://www.impinj.com",
                "product_name": "Impinj Speedway R700 RAIN RFID Reader",
                "model_name": "R700",
            },
        snmp_identity={
                "sys_descr": "Impinj Speedway R700 RAIN RFID Reader V8.2.0",
                "sys_object_id": "1.3.6.1.4.1.25882.1.1",
                "sys_name": "SPEEDWAY-R700-001",
                "sys_location": "Dock Door",
                "sys_contact": "rfid@warehouse.local",
            },
    ),
    DeviceTemplate(
        id="kuka/kmp-mobile-platform/kmp-1500",
        vendor="KUKA",
        vendor_family="KMP Mobile Platform",
        model="KMP 1500",
        model_name="KMP 1500",
        device_type="agv",
        description="KUKA KMP 1500",
        oui_prefixes=['00:1A:28', '00:1F:29', '00:10:DC'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 25.0,
                "mean_ms": 8.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
                "outlier_probability": 0.01,
            },
        error_behavior={
                "timeout_probability": 0.0005,
                "retry_behavior": True,
                "max_retries": 3,
            },
        supported_protocols=['ethernet_ip', 'profinet'],
        firmware_variants=[FirmwareVariant(
            version="8.6.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        ethernet_ip_identity={
                "vendor_id": 368,
                "device_type": 43,
                "product_code": 1500,
                "revision_major": 8,
                "revision_minor": 6,
                "serial_number": 1263358001,
                "product_name": "KMP 1500 Mobile Platform",
                "state": 3,
            },
        profinet_identity={
                "vendor_id": 368,
                "device_id": 5376,
                "station_name": "kmp1500",
                "device_type": "KMP 1500 Mobile Platform",
                "device_role": 1,
                "sw_release": "V8.6.0",
                "im0_manufacturer": "KUKA Roboter GmbH",
                "im0_order_id": "KMP 1500",
                "im0_hw_revision": 3,
                "im0_sw_revision": "V8.6.0",
            },
    ),
    DeviceTemplate(
        id="kuka/kmp-mobile-platform/kmp-600",
        vendor="KUKA",
        vendor_family="KMP Mobile Platform",
        model="KMP 600",
        model_name="KMP 600",
        device_type="agv",
        description="KUKA KMP 600",
        oui_prefixes=['00:1A:28', '00:1F:29', '00:10:DC'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 30.0,
                "mean_ms": 10.0,
                "std_dev_ms": 5.0,
                "distribution": "gaussian",
            },
        supported_protocols=['ethernet_ip', 'profinet'],
        firmware_variants=[FirmwareVariant(
            version="8.5.2",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        ethernet_ip_identity={
                "vendor_id": 368,
                "device_type": 43,
                "product_code": 600,
                "revision_major": 8,
                "revision_minor": 5,
                "product_name": "KMP 600 Mobile Platform",
                "state": 3,
            },
        profinet_identity={
                "vendor_id": 368,
                "device_id": 1536,
                "station_name": "kmp600",
                "device_type": "KMP 600 Mobile Platform",
                "device_role": 1,
                "sw_release": "V8.5.2",
                "im0_manufacturer": "KUKA Roboter GmbH",
                "im0_order_id": "KMP 600",
            },
    ),
    DeviceTemplate(
        id="kuka/fleet-management/kuka-fleetmanager",
        vendor="KUKA",
        vendor_family="Fleet Management",
        model="KUKA.FleetManager",
        model_name="KUKA.FleetManager",
        device_type="fleet_manager",
        description="KUKA KUKA.FleetManager",
        oui_prefixes=['00:1A:28', '00:1F:29', '00:10:DC'],
        tcp_stack={
                "ttl": 64,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 1.0,
                "max_ms": 15.0,
                "mean_ms": 5.0,
                "std_dev_ms": 3.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'ethernet_ip', 'profinet'],
        firmware_variants=[FirmwareVariant(
            version="3.2.1",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "KUKA Roboter GmbH",
                "product_code": "FleetManager",
                "major_minor_revision": "3.2.1",
                "product_name": "KUKA Fleet Management System",
                "model_name": "FleetManager",
            },
        ethernet_ip_identity={
                "vendor_id": 368,
                "device_type": 12,
                "product_code": 9001,
                "revision_major": 3,
                "revision_minor": 2,
                "product_name": "KUKA.FleetManager",
                "state": 3,
            },
        profinet_identity={
                "vendor_id": 368,
                "device_id": 36865,
                "station_name": "kuka-fleetmgr",
                "device_type": "KUKA Fleet Manager",
                "device_role": 2,
                "sw_release": "V3.2.1",
                "im0_manufacturer": "KUKA Roboter GmbH",
                "im0_order_id": "FleetManager",
                "im0_hw_revision": 2,
                "im0_sw_revision": "V3.2.1",
            },
    ),
    DeviceTemplate(
        id="mir/mir-fleet/mir-fleet",
        vendor="MiR",
        vendor_family="MiR Fleet",
        model="MiR Fleet",
        model_name="MiR Fleet",
        device_type="agv",
        description="MiR MiR Fleet",
        oui_prefixes=['00:1E:06'],
        tcp_stack={
                "ttl": 64,
                "window_size": 65535,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 2.0,
                "max_ms": 20.0,
                "mean_ms": 6.0,
                "std_dev_ms": 4.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp'],
        firmware_variants=[FirmwareVariant(
            version="3.8.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Mobile Industrial Robots A/S",
                "product_code": "MiR Fleet",
                "major_minor_revision": "3.8.0",
                "product_name": "MiR Fleet Management System",
                "model_name": "MiR Fleet",
            },
    ),
    DeviceTemplate(
        id="mir/mir-mobile-robots/mir100",
        vendor="MiR",
        vendor_family="MiR Mobile Robots",
        model="MiR100",
        model_name="MiR100",
        device_type="agv",
        description="MiR MiR100",
        oui_prefixes=['00:1E:06'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
                "df_flag": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 50.0,
                "mean_ms": 15.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
                "outlier_probability": 0.02,
            },
        error_behavior={
                "timeout_probability": 0.001,
                "retry_behavior": True,
                "max_retries": 3,
            },
        supported_protocols=['modbus_tcp', 'ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="3.12.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Mobile Industrial Robots A/S",
                "product_code": "MiR100",
                "major_minor_revision": "3.12.0",
                "vendor_url": "https://www.mobile-industrial-robots.com",
                "product_name": "MiR100 Autonomous Mobile Robot",
                "model_name": "MiR100",
            },
        ethernet_ip_identity={
                "vendor_id": 0,
                "device_type": 12,
                "product_code": 100,
                "revision_major": 3,
                "revision_minor": 12,
                "product_name": "MiR100",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="mir/mir-mobile-robots/mir250",
        vendor="MiR",
        vendor_family="MiR Mobile Robots",
        model="MiR250",
        model_name="MiR250",
        device_type="agv",
        description="MiR MiR250",
        oui_prefixes=['00:1E:06'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 50.0,
                "mean_ms": 15.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="3.12.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Mobile Industrial Robots A/S",
                "product_code": "MiR250",
                "major_minor_revision": "3.12.0",
                "vendor_url": "https://www.mobile-industrial-robots.com",
                "product_name": "MiR250 Autonomous Mobile Robot",
                "model_name": "MiR250",
            },
        ethernet_ip_identity={
                "vendor_id": 0,
                "device_type": 12,
                "product_code": 250,
                "revision_major": 3,
                "revision_minor": 12,
                "product_name": "MiR250",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="mir/mir-mobile-robots/mir500",
        vendor="MiR",
        vendor_family="MiR Mobile Robots",
        model="MiR500",
        model_name="MiR500",
        device_type="agv",
        description="MiR MiR500",
        oui_prefixes=['00:1E:06'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 60.0,
                "mean_ms": 18.0,
                "std_dev_ms": 10.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'ethernet_ip'],
        firmware_variants=[FirmwareVariant(
            version="3.12.0",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Mobile Industrial Robots A/S",
                "product_code": "MiR500",
                "major_minor_revision": "3.12.0",
                "vendor_url": "https://www.mobile-industrial-robots.com",
                "product_name": "MiR500 Autonomous Mobile Robot",
                "model_name": "MiR500",
            },
        ethernet_ip_identity={
                "vendor_id": 0,
                "device_type": 12,
                "product_code": 500,
                "revision_major": 3,
                "revision_minor": 12,
                "product_name": "MiR500",
                "state": 3,
            },
    ),
    DeviceTemplate(
        id="zebra/fixed-rfid/fx7500",
        vendor="Zebra",
        vendor_family="Fixed RFID",
        model="FX7500",
        model_name="FX7500",
        device_type="rfid_reader",
        description="Zebra FX7500",
        oui_prefixes=['00:A0:F8', '00:23:68', 'AC:3F:A4'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 45.0,
                "mean_ms": 15.0,
                "std_dev_ms": 8.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="3.28.10",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Zebra Technologies Corporation",
                "product_code": "FX7500",
                "major_minor_revision": "3.28.10",
                "product_name": "Zebra FX7500 4-Port RFID Reader",
                "model_name": "FX7500",
            },
        snmp_identity={
                "sys_descr": "Zebra FX7500 Fixed RFID Reader V3.28.10",
                "sys_object_id": "1.3.6.1.4.1.10642.1.2",
                "sys_name": "FX7500-001",
            },
    ),
    DeviceTemplate(
        id="zebra/fixed-rfid/fx9600",
        vendor="Zebra",
        vendor_family="Fixed RFID",
        model="FX9600",
        model_name="FX9600",
        device_type="rfid_reader",
        description="Zebra FX9600",
        oui_prefixes=['00:A0:F8', '00:23:68', 'AC:3F:A4'],
        tcp_stack={
                "ttl": 64,
                "window_size": 29200,
                "mss": 1460,
                "sack_permitted": True,
                "timestamps_enabled": True,
            },
        response_timing={
                "min_ms": 5.0,
                "max_ms": 50.0,
                "mean_ms": 18.0,
                "std_dev_ms": 10.0,
                "distribution": "gaussian",
            },
        supported_protocols=['modbus_tcp', 'snmp'],
        firmware_variants=[FirmwareVariant(
            version="3.29.15",
            release_date=date(2024, 1, 1),
            is_default=True,
            is_latest=True,
        )],
        modbus_identity={
                "vendor_name": "Zebra Technologies Corporation",
                "product_code": "FX9600",
                "major_minor_revision": "3.29.15",
                "product_name": "Zebra FX9600 8-Port RFID Reader",
                "model_name": "FX9600",
            },
        snmp_identity={
                "sys_descr": "Zebra FX9600 Fixed RFID Reader V3.29.15",
                "sys_object_id": "1.3.6.1.4.1.10642.1.1",
                "sys_name": "FX9600-001",
                "sys_location": "Portal",
                "sys_contact": "rfid@warehouse.local",
            },
    ),
]
