"""Tests for conduit auto-generation service."""

import pytest

from app.services.conduit_service import (
    PURDUE_ADJACENCY,
    DEFAULT_CONDUIT_PROTOCOLS,
    generate_default_conduits,
)


class TestPurdueAdjacency:
    """Test Purdue level adjacency definitions."""

    def test_adjacency_pairs_defined(self):
        """All expected adjacency pairs exist."""
        assert (0, 1) in PURDUE_ADJACENCY
        assert (1, 2) in PURDUE_ADJACENCY
        assert (2, 3) in PURDUE_ADJACENCY
        assert (3, 3.5) in PURDUE_ADJACENCY
        assert (3.5, 4) in PURDUE_ADJACENCY

    def test_adjacency_lower_first(self):
        """All adjacency pairs have lower level first."""
        for low, high in PURDUE_ADJACENCY:
            assert low < high

    def test_protocols_defined_for_each_pair(self):
        """Each adjacency pair has a default protocol list."""
        for pair in PURDUE_ADJACENCY:
            assert pair in DEFAULT_CONDUIT_PROTOCOLS
            assert len(DEFAULT_CONDUIT_PROTOCOLS[pair]) > 0


class TestGenerateDefaultConduits:
    """Tests for generate_default_conduits()."""

    def test_empty_zones_returns_empty(self):
        """No zones → no conduits."""
        result = generate_default_conduits({})
        assert result == {}

    def test_single_zone_no_conduits(self):
        """One zone has nothing to pair with."""
        zones = {
            "z1": {"id": "z1", "name": "Zone A", "level": 1}
        }
        result = generate_default_conduits(zones)
        assert result == {}

    def test_adjacent_levels_creates_conduit(self):
        """Two zones at adjacent Purdue levels produce a conduit."""
        zones = {
            "z1": {"id": "z1", "name": "Field", "level": 0},
            "z2": {"id": "z2", "name": "Control", "level": 1},
        }
        result = generate_default_conduits(zones)
        assert len(result) == 1

        conduit = list(result.values())[0]
        assert conduit["sourceZoneId"] == "z1"  # lower level
        assert conduit["targetZoneId"] == "z2"  # higher level
        assert conduit["direction"] == "bidirectional"
        assert conduit["autoGenerated"] is True
        assert "profinet" in conduit["allowedProtocols"]

    def test_non_adjacent_levels_no_conduit(self):
        """Non-adjacent levels (e.g., 0 and 3) produce no conduit."""
        zones = {
            "z1": {"id": "z1", "name": "Field", "level": 0},
            "z2": {"id": "z2", "name": "Operations", "level": 3},
        }
        result = generate_default_conduits(zones)
        assert result == {}

    def test_zones_without_level_skipped(self):
        """Zones without a level field are skipped."""
        zones = {
            "z1": {"id": "z1", "name": "Zone A"},
            "z2": {"id": "z2", "name": "Zone B", "level": 1},
        }
        result = generate_default_conduits(zones)
        assert result == {}

    def test_multiple_adjacency_pairs(self):
        """Three zones spanning L0-L1-L2 produce two conduits."""
        zones = {
            "z0": {"id": "z0", "name": "Field", "level": 0},
            "z1": {"id": "z1", "name": "Control", "level": 1},
            "z2": {"id": "z2", "name": "Supervisory", "level": 2},
        }
        result = generate_default_conduits(zones)
        assert len(result) == 2

        # Check both adjacency pairs are covered
        zone_pairs = set()
        for conduit in result.values():
            zone_pairs.add((conduit["sourceZoneId"], conduit["targetZoneId"]))
        assert ("z0", "z1") in zone_pairs
        assert ("z1", "z2") in zone_pairs

    def test_dmz_levels(self):
        """DMZ (3.5) creates conduits with L3 and L4."""
        zones = {
            "z3": {"id": "z3", "name": "Operations", "level": 3},
            "dmz": {"id": "dmz", "name": "DMZ", "level": 3.5},
            "z4": {"id": "z4", "name": "Enterprise", "level": 4},
        }
        result = generate_default_conduits(zones)
        assert len(result) == 2

    def test_accepts_list_format(self):
        """Zones can be passed as a list (template format)."""
        zone_list = [
            {"id": "z1", "name": "Field", "level": 0},
            {"id": "z2", "name": "Control", "level": 1},
        ]
        result = generate_default_conduits(zone_list)
        assert len(result) == 1

    def test_lower_level_always_source(self):
        """Source zone ID is always the lower Purdue level."""
        # Reverse order in dict to test ordering logic
        zones = {
            "z2": {"id": "z2", "name": "Supervisory", "level": 2},
            "z1": {"id": "z1", "name": "Control", "level": 1},
        }
        result = generate_default_conduits(zones)
        conduit = list(result.values())[0]
        assert conduit["sourceZoneId"] == "z1"
        assert conduit["targetZoneId"] == "z2"

    def test_conduit_name_uses_zone_names(self):
        """Conduit name contains both zone names."""
        zones = {
            "z1": {"id": "z1", "name": "Field Devices", "level": 0},
            "z2": {"id": "z2", "name": "Basic Control", "level": 1},
        }
        result = generate_default_conduits(zones)
        conduit = list(result.values())[0]
        assert "Field Devices" in conduit["name"]
        assert "Basic Control" in conduit["name"]

    def test_same_level_no_conduit(self):
        """Two zones at the same level don't produce a conduit."""
        zones = {
            "z1": {"id": "z1", "name": "Cell A", "level": 1},
            "z2": {"id": "z2", "name": "Cell B", "level": 1},
        }
        result = generate_default_conduits(zones)
        assert result == {}

    def test_full_purdue_stack(self):
        """Full L0-L4 stack produces 5 conduits (one per adjacency pair)."""
        zones = {
            "z0": {"id": "z0", "name": "L0", "level": 0},
            "z1": {"id": "z1", "name": "L1", "level": 1},
            "z2": {"id": "z2", "name": "L2", "level": 2},
            "z3": {"id": "z3", "name": "L3", "level": 3},
            "dmz": {"id": "dmz", "name": "DMZ", "level": 3.5},
            "z4": {"id": "z4", "name": "L4", "level": 4},
        }
        result = generate_default_conduits(zones)
        assert len(result) == 5

    def test_unique_ids(self):
        """All generated conduit IDs are unique."""
        zones = {
            "z0": {"id": "z0", "name": "L0", "level": 0},
            "z1": {"id": "z1", "name": "L1", "level": 1},
            "z2": {"id": "z2", "name": "L2", "level": 2},
        }
        result = generate_default_conduits(zones)
        ids = [c["id"] for c in result.values()]
        assert len(ids) == len(set(ids))
