# PacketArch — OT Traffic Simulation Platform
# Copyright (c) 2026 Rocky Smith <rocky.d.smith@proton.me>
# Licensed under GPL-3.0. See LICENSE at the repo root.
"""Conduit auto-generation from Purdue model adjacency.

Generates default conduits for zone pairs at adjacent Purdue levels,
following IEC 62443 zone and conduit architecture.
"""

from typing import Any

# Purdue model level adjacency pairs (lower, upper)
PURDUE_ADJACENCY: list[tuple[float, float]] = [
    (0, 1),      # Field ↔ Basic Control
    (1, 2),      # Basic Control ↔ Area Supervisory
    (2, 3),      # Area Supervisory ↔ Site Operations
    (3, 3.5),    # Site Operations ↔ DMZ
    (3.5, 4),    # DMZ ↔ Enterprise
]

# Default allowed protocols per Purdue level pair.
#
# Modern OT realism: OPC UA is a primary IT/OT bridge protocol that
# traverses L1→L2→L3 routinely (S7-1500 OPC UA server feeds HMIs, area
# historians, MES). SNMP is universally polled for monitoring at every
# level pair (NMS reaches all the way down). HTTPS is increasingly used
# for engineering tool web UIs and REST APIs at L2+.
DEFAULT_CONDUIT_PROTOCOLS: dict[tuple[float, float], list[str]] = {
    (0, 1): [
        "profinet", "ethernet_ip", "modbus_tcp",
        "profisafe", "cip_safety", "bacnet",
        "snmp",  # NMS monitoring reaches L0 instrumentation
    ],
    (1, 2): [
        "s7comm", "s7comm_plus", "ethernet_ip", "modbus_tcp",
        "profinet", "bacnet", "snmp",
        "opc_ua",  # Modern PLCs serve OPC UA up to HMI/SCADA
        "iec61850", "iec104", "dnp3",  # substation + utility scada
    ],
    (2, 3): [
        "modbus_tcp", "ethernet_ip", "s7comm", "snmp", "bacnet",
        "opc_ua",  # SCADA/historian aggregate via OPC UA from area
        "https",  # Web UIs / REST APIs (FactoryTalk, EcoStruxure, WinCC)
        "iec61850", "iec104", "dnp3",
    ],
    (3, 3.5): [
        "snmp",
        "opc_ua",  # IDMZ OPC UA aggregator → enterprise replica
        "https",  # patch staging, AV mgmt, reverse proxies
    ],
    (3.5, 4): [
        "snmp",
        "https",  # most IT/enterprise traffic is HTTPS-wrapped
        "opc_ua",  # historian replica → enterprise BI consumers
    ],
}


def generate_default_conduits(
    zones: dict[str, Any] | list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    """Auto-generate conduits from Purdue level adjacency.

    For every pair of zones whose Purdue levels are adjacent,
    creates a bidirectional conduit with sensible protocol defaults.

    Args:
        zones: Zone definitions — either a dict keyed by zone ID
               or a list of zone dicts (template format).

    Returns:
        Dict of conduit ID → conduit definition.
    """
    # Normalize to list
    if isinstance(zones, dict):
        zone_list = list(zones.values())
    else:
        zone_list = list(zones)

    conduits: dict[str, dict[str, Any]] = {}
    conduit_idx = 0

    for i, z1 in enumerate(zone_list):
        for z2 in zone_list[i + 1:]:
            level1 = z1.get("level")
            level2 = z2.get("level")
            if level1 is None or level2 is None:
                continue

            pair = (min(level1, level2), max(level1, level2))
            if pair not in PURDUE_ADJACENCY:
                continue

            conduit_idx += 1
            cid = f"conduit_{conduit_idx:03d}"

            # Order: lower Purdue level first
            if z1.get("level", 0) <= z2.get("level", 0):
                lower_zone, upper_zone = z1, z2
            else:
                lower_zone, upper_zone = z2, z1

            lower_name = lower_zone.get("name", lower_zone.get("id", "?"))
            upper_name = upper_zone.get("name", upper_zone.get("id", "?"))

            conduits[cid] = {
                "id": cid,
                "name": f"{lower_name} \u2194 {upper_name}",
                "sourceZoneId": lower_zone.get("id", ""),
                "targetZoneId": upper_zone.get("id", ""),
                "direction": "bidirectional",
                "allowedProtocols": DEFAULT_CONDUIT_PROTOCOLS.get(pair, []),
                "securityLevel": "standard",
                "autoGenerated": True,
            }

    return conduits
