# PacketArch — OT Traffic Simulation Platform
# Copyright (c) 2026 Rocky Smith <rocky.d.smith@proton.me>
# Licensed under GPL-3.0. See LICENSE at the repo root.
"""PacketArch Agent version information."""

# Semantic versioning: MAJOR.MINOR.PATCH
# - MAJOR: Breaking changes to agent/server protocol
# - MINOR: New features, backward compatible
# - PATCH: Bug fixes, minor improvements
VERSION = "1.49.0"

# Version history:
# 1.49.0 - Verification bump (no agent code change) to exercise the now-fixed self-update path end-to-end on a connectivity-constrained CML-lab agent. Gives the 1.48.0 agents a newer image to actually self-update TO (same-SHA loads are skipped as "already up to date"), proving the updater container (run from packetarch-agent:latest, no apk/no pull) recreates the agent without stranding. See 1.48.0.
# 1.48.0 - ACTUAL self-update connectivity fix lands in code. The detached updater container ran alpine:latest + `apk add docker-cli docker-cli-compose`, fetching the docker CLI from the internet AT UPDATE TIME — after `docker compose down` had already removed the agent. On a VM without reliable outbound internet the apk step failed/hung, stranding the agent (frozen "restarting", no container left to revive). The updater now runs from packetarch-agent:latest itself (entrypoint=/bin/sh -c), which already bundles docker + compose (per Dockerfile) and is guaranteed present locally, so the update needs NO apk and NO image pull. Both the compose path and the docker-run fallback updated. NOTE: v1.47.0's commit (f65e869) claimed this fix but only bumped the version string; the served 1.47.0 image was built from still-buggy code. This 1.48.0 build is the first to actually contain the code fix.
# 1.47.0 - (MISLABELED) commit f65e869 claimed the self-update connectivity fix but only changed this version string — the code fix did not land until 1.48.0. Do not ship the 1.47.0 agent image.
# 1.46.0 - Release-pipeline verification bump (no agent code change). Cut alongside app v1.7.0 to exercise the agent image build + install/self-update path end-to-end after the Local Sensor Labs work.
# 1.45.1 - Resolve IEC 60870-5-104 protocol alias. Templates and the identity
#   layer spell it "iec104" but the runtime ProtocolType value (and engine
#   registration) is "iec_104", so "iec104" flows resolved to an unknown
#   ProtocolType and were silently dropped by traffic_generator/tasks.py.
#   Added "iec104" -> "iec_104" to PROTOCOL_ALIASES in protocol_engines/
#   protocols.py. Fixes silently-dropped IEC-104 flows in the energy/power
#   templates (electrical_substation, grid_control_center, etc.).
# 1.45.0 - Energy/power vertical expansion. Adds (1) IEEE C37.118.2-2011 synchrophasor engine in protocol_engines/synchrophasor/ — PMU/PDC command/CFG-2/DATA frame builders with CRC-CCITT trailer, registered on new ProtocolType.C37118 (default port 4712 TCP / 4713 UDP). SEL-411L and SEL-787 templates ship c37118_identity so they stream real synchrophasor data. (2) Fingerprint ProtocolType.IEC61850 added (engine was already present, just unreachable through the supported_protocols enum). MMS/GOOSE/SV strings now alias to iec61850 at runtime. (3) Six new attack action generators in attacks/ics_actions.py: iec104_breaker_open (ASDU 46 select-and-execute), iec104_select_before_operate_abuse, iec61850_goose_spoof (L2 multicast 01:0C:CD:01:00:01, EtherType 0x88B8), iec61850_mms_write (TPKT+COTP+MMS over TCP/102), c37118_phasor_spoof (UDP/4713 with abnormal frequency), dnp3_unsolicited_flood. (4) Two new playbooks: INDUSTROYER2_LIKE (S1072, 2022 Ukraine IEC-104 + 61850 focus) and VOLT_TYPHOON_LIKE (G1017, LotL stealth recon).
# 1.44.1 - Fix agent self-update "already up to date" false-positive when the agent shares a Docker daemon with the PacketArch backend builder (e.g. local LocalDiag agent on the dev host). The previous check compared the freshly-loaded image SHA against the `packetarch-agent:latest` tag's current SHA — but when the backend builds the image in-place, the tag is bumped BEFORE UPDATE_AGENT reaches the agent, so the comparison says "same image, skip" even though the running container is still on the older layers. `_handle_update_agent` now also captures the running container's actual image SHA (via HOSTNAME → container.image.id) and uses THAT as the comparison reference. Separate-daemon agents (e.g. remote TrafficGen02) behave the same as before since their tag and container image always agree pre-update.
# 1.44.0 - Attack after-action report telemetry. AttackOrchestrator now captures per-action packet counts, fire timestamps, targets-hit list, and protocol IOCs (attacker IP, target IPs, ports, register addresses, function codes, SNMP communities, etc.) into a structured AttackReport dataclass that lives alongside live state. Report rides the existing agent→backend STATUS pipeline (embedded as `attack.report` field) so no new WebSocket plumbing. New backend endpoints: `GET /attacks/{id}/report` returns the current report, `GET /attacks/{id}/history` returns persisted past runs. On completion, reports are snapshotted into `scenario.definition.attack_history[]` (cap 50, deduped by playbook_id+started_at) so they survive deployment teardown.
# 1.43.0 - BACnet device_instance uniqueness fix. The BACnet engine (`_get_bacnet_identity`, `_get_device_instance`) and the ambient discovery I-Am broadcaster were reading `device_instance` from the raw fingerprint snapshot, which holds the template's shared value (e.g. all 25 "Niagara JACE Field Controller" instances claimed device_instance=1258502). CV uses BACnet device_instance as the canonical identity key, so all 25 devices collapsed into one component with bouncing MACs. Observed 2026-05-13 on a Commercial Office BMS deploy: 47 physical BACnet devices → only 6 distinct device_instance values, one shared by 25 devices. Engine now pulls from `flow.destination.fingerprint_applicator.bacnet_identity` (which has UniqueIdentifierGenerator's per-instance values). Ambient generator computes the per-instance value inline via `UniqueIdentifierGenerator.generate_bacnet_device_instance(device_id, scenario_id, base_instance=template_value)`.
# 1.42.1 - Rate-limit identity-vendor-id warnings. The "CIP Identity Object missing vendor_id" and "PROFINET vendor_id absent" warnings were firing per-poll-cycle (15-30× per scenario startup, then continuously through PROFINET DCP traffic) for any scenario whose stored fingerprint snapshot pre-dates the device-template vendor_id backfills. The warnings are correct (the snapshot is stale, traffic still goes out) but the spam buried real issues. Now logged once per (vendor, model) tuple via module-level dedupe sets in profinet/packets.py and identity/ethernet_ip_builder.py, plus once per FingerprintApplicator instance in fingerprint_applicator.py.
# 1.42.0 - Per-vendor TLS ClientHello profiles. The v1.41 wall-clock heartbeat thread restored cloud_service packet emission, but CV rendered jump_server / bastion devices with a Canon-printer icon because the minimalist 4-cipher ClientHello matched the JA3 hash of Canon iR-series embedded TLS clients. Adds `windows_schannel_2016` profile (25 ciphers, full SChannel 1607 extension set incl. extended_master_secret, signature_algorithms, ALPN, session_ticket, status_request) and selects it for Microsoft-vendor / jump_server / bastion / rdp_gateway sources via `CloudServiceConversationState.tls_profile`. The default `embedded_minimal` profile is unchanged — eWON / cellular gateway flows still emit the small embedded shape, which is correct for them.
# 1.41.0 - REAL FIX: cloud_service heartbeats now run on a dedicated wall-clock background thread, NOT via the orchestrator's virtual-time event heap. Root cause: PROFINET-cyclic flows at 8 ms intervals (3 PN flows × 125 pps × 25 s window ≈ 9000 packets at vtime 5-15 s) flood the heap. Scapy.sendp() throughput is ~60 pps, so virtual time runs ~10× slower than wall clock. A heartbeat scheduled at vtime 36 s thus didn't fire until ~9 min of wall time — observed as "EWON has no external comms" (4 cloud_service packets in 22 min). Heartbeats are infrastructure keep-alives, not OT poll cycles; they belong on a wall-clock cadence. `_build_cloud_heartbeat_spec()` replaces `_create_cloud_flow()`, and `_run_cloud_heartbeats()` is the per-scenario thread that calls `CloudServiceEngine.generate_poll_cycle()` and `scapy.sendp()` directly. Stats are reported back via `orchestrator.stats.record_packet("cloud_service", …)` so the dashboard breakdown still works. The v1.37 _HEARTBEAT_PROTOCOLS bypass-adaptive code remains for SSH/TELNET/RDP/HTTPS flows, which still go through the heap but with real source-and-target devices and longer intervals (less likely to starve).
# 1.40.0 - Diagnostic: INFO-level POLL_FIRE and HEARTBEAT_FIRST_POLL_SCHEDULED log entries for all heartbeat protocols (cloud_service/ssh/telnet/rdp/https) — needed to pin down whether the agent ever fires the first cloud poll event in production.
# 1.39.0 - Revert v1.37 synthetic gateway MAC for cloud_service flows back to broadcast ff:ff:ff:ff:ff:ff. The synthetic 02:00:00:xx:xx:xx MAC was causing the agent's Linux raw-socket path to silently drop frames (no scapy exception, just never reached the wire), regressing cloud_service from 4 pkts/22 min (slow but visible) to 0 pkts/3 min. Keeps the v1.37 heartbeat-bypass-adaptive fix and v1.38 per-protocol injection error logging.
# 1.38.0 - Diagnostic: per-protocol packet-injection error logging in UnifiedOrchestrator main loop. Previously, if scapy.sendp() raised for any single packet (kernel filter, synthetic MAC rejection, malformed frame edge case), the exception propagated up and silently exited the entire orchestration run loop — but the agent's STATUS stream kept reporting the last-known packet count, masking the failure as "scenario running but cloud_service silent." Now each protocol logs its first injection failure with reason and continues processing other events.
# 1.37.0 - Restore eWON/jump-server external comms: cloud_service heartbeats were observed firing only once per deployment (4 pkts in 22 min) because the AdaptiveController's phase rate-scaling stretched the 30 s heartbeat by ÷rate_multiplier — during the "startup" phase (rate=0.1) the interval ballooned to 5 min, and any active_flow_percent gate could effectively suspend the flow for an entire phase. Heartbeat protocols (CLOUD_SERVICE, SSH, TELNET, RDP, HTTPS) now bypass adaptive adjustment in UnifiedOrchestrator._handle_poll_event. Also: cloud destination MAC is now a synthetic gateway unicast (02:00:00:xx:xx:xx derived from the device's gateway IP) instead of broadcast ff:ff:ff:ff:ff:ff, so SPAN mirrors and CV DPI don't treat the frame as an ARP-style broadcast. Backend scenario_enrichment._REMOTE_ACCESS_DEVICE_TYPES expanded from 4 to 15 device types (vpn_gateway, cellular_gateway, bastion, rdp_gateway, industrial_router, iot_gateway, edge_gateway, ewon, remote_access_gateway, ...) so every remote-access role gets a cloud link auto-attached at deploy.
# 1.36.0 - Remote-access protocol support: adds ProtocolType.SSH/TELNET/RDP/HTTPS that share the CloudServiceEngine for TCP+TLS-shaped heartbeats. Port mapping in protocols.py routes ssh→22, telnet→23, rdp→3389, https→443 so CV identifies by destination port. Jump server templates now declare these protocols and the flow-protocol repair priority ranks them above SNMP, so a jump_server→switch flow snaps to ssh instead of snmp. Fixes the long tail of irrational-flow audit warnings around remote-access devices.
# 1.35.0 - Clean Demo Mode v2: extends suppression to ambient PROFINET DCP IdentifyRequest multicasts. CV correlation creates a phantom "Siemens xx:xx:xx" component for every MAC seen on an L2-only frame and never merges with the IP-bearing identified component for the same MAC. Configured PROFINET flow startups still emit DCP for fingerprinting; the new ensure_device_flow_coverage enrichment guarantees every device has at least one IP-based flow that fingerprints it via L3 traffic. Plumbed `clean_demo_mode` through to BackgroundNoiseGenerator so both agent (live) and PCAP paths suppress identically.
# 1.34.0 - Clean Demo Mode (extensible scenario flag): definition.clean_demo_mode (default false). When true, the agent injects clean_demo_mode=True into each FlowContext.config and protocol engines suppress traffic that confuses asset-classification DPI tools. v1 suppression: PROFINET RT cyclic I/O frames (PN-IO) — eliminates the phantom "Vendor xx:xx:xx" components CV creates per PN-IO source MAC. Future suppressions go behind the same flag (CIP Class 1 cyclic, S7 cyclic, anything similar).
# 1.33.0 - LLDP-only Phase 0 burst. After v1.31.0's malformed DCP-to-multicast made phantoms worse, this version reintroduces an early identity burst using ONLY the standard LLDP protocol (well-formed multicast 01:80:C2:00:00:0E that CV correctly parses). Three LLDP advertisements per device at t≈20/180/400ms — before PROFINET I/O cyclic data begins. Goal: give CV a MAC→system_name binding before PN-IO frames create phantom components for the same MAC. No DCP multicast, no malformed frames.
# 1.32.0 - Revert v1.31.0 Phase 0 identity burst. Sending IdentifyResponse PDU to multicast 01:0E:CF:00:00:01 turned out to be malformed PROFINET DCP — real Hello messages use ServiceID 0x06 / FrameID 0xFEFC, not the IDENTIFY ServiceID 0x05. CV interpreted each malformed multicast frame as a new event and created MORE phantom components instead of consolidating. Phase 0 schedule and `_handle_profinet_hello` removed; `burst` flag remains in `_handle_lldp` and `_handle_profinet_dcp` (harmless when unused).
# 1.31.0 - PROFINET identity burst (option #1): adds Phase 0 to BackgroundNoiseGenerator that fires 3 LLDP advertisements (t=20-430ms) and 3 unsolicited DCP Hello multicasts (t=50-530ms) per PROFINET device at scenario start. The DCP Hello is a new ambient event that emits IdentifyResponse to multicast 01:0E:CF:00:00:01 (instead of the previous unicast-back-to-requester) so CV's mirror reliably catches the full identity payload — name+IP+vendor+model — for every device before PROFINET I/O cyclic frames begin (~400ms). Should eliminate the "Siemens xx:xx:xx" phantom components CV was creating for every PN-IO source MAC.
# 1.30.0 - Fix v1.29.0 zone field name: orchestrator_pool read `dev.get("zone")` but the frontend stores zone membership as `zoneId` (camelCase). With the wrong field every device's purdue_level resolved to None, so the cell-isolation guard added in v1.29.0 never engaged and ambient unicast pollers continued crossing cells. Now matches cell_isolation._zone_of priority (zoneId > zone_id > zone).
# 1.29.0 - Cell-isolation-aware ambient discovery: BackgroundNoiseGenerator._pick_query_source now refuses cross-cell unicast pollers (SNMP/Modbus/EnIP/S7/NTP) when scenario isolation is conduit_gated or strict_northbound. Falls back to L3+ "manager" zones instead of peer cells. Layer-2 broadcasts (LLDP/STP/CDP/Who-Is/DCP) unchanged — already zone-local. Lets users keep full CV fingerprinting while preserving strict cell isolation.
# 1.28.0 - Per-scenario broadcast/multicast toggle: definition.broadcast_traffic_enabled (default true). When false, ambient noise generator (ARP, NTP, LLDP, STP, CDP, DHCP, IGMP, BACnet Who-Is, PROFINET DCP, SNMP traps) is skipped on the agent. Same flag also gates PCAP generation in TrafficOrchestrator.
# 1.27.0 - Purdue-aware cell isolation: runtime gate that drops east/west cell↔cell flows (modes: off / conduit_gated / strict_northbound). Same protocol_engines/cell_isolation.py shared with backend so PCAP and live traffic enforce identically.
# 1.26.0 - CV DPI malformation fixes: PROFINET DCP BlockInfo qualifier (was missing on every response block, all Identify Responses dissected as malformed), OPC UA OPNF SecureChannelId field (4 bytes, was missing), OPC UA IP/TCP checksum recompute (was 0 / RFC 791 invalid - CV silently dropped these packets before DPI), EtherNet/IP ForwardOpen wrapped in EIP encap+CPF+CIP MR (was raw CIP service data), ForwardOpen reply struct format (vendor_id UDINT→UINT, t_to_o_api restored, 28b → 30b per CIP Vol 1 §3-5.5.4.1). Plus protocol→port routing (PROTOCOL_DEFAULT_PORTS / get_default_port) and variant alias resolution (s7comm_plus / profisafe / cip_safety) so flows actually reach their engines and land on the correct ports.
# 1.25.0 - Synchronized attack lifecycle with deployment - STOP_SCENARIO now auto-stops attack orchestrator, prevents orphaned attacks
# 1.24.0 - Add 15 Snort/Suricata rule-triggering attack actions for IDS validation (SNORT_VALIDATION playbook, ICS/OT, C2, exfiltration signatures)
# 1.23.2 - Fix attack stage stuck at 0s: wall-time stage advancement on every event loop iteration (prevents virtual-time lag), fix injection config mapping
# 1.23.1 - Fix attack state in event-driven STATUS path, trigger immediate status after injection for faster confirmation
# 1.23.0 - Hot-attach attack playbooks: INJECT_ATTACK command for mid-run playbook injection into running deployments
# 1.22.0 - CV fingerprint gap fix: 301/301 templates with explicit snmp_identity, SNMP pre-startup timing (sysName before protocol flows), fix duplicate CIP serials (SerialNumberGenerator moved to protocol_engines), sysName priority = device_name over template
# 1.21.0 - Fix OUI misattributions (KUKA/Fanuc/SICK/HMS), early-burst discovery (3 cycles in first 90s for faster CV fingerprinting)
# 1.20.0 - Universal SNMP discovery: all fingerprinted devices get SNMP GET/Response for CV fingerprinting, vendor-specific sysObjectID synthesis, merge device definition protocols into ambient discovery
# 1.19.1 - Eliminate phantom devices: all ambient handlers use real scenario devices as query sources instead of fake gateway IPs (02:00:00:00:00:01)
# 1.19.0 - Ambient discovery: self-response for BACnet/PROFINET/ENIP/S7 (source-only devices), BACnet ReadProperty identity, fix property_type encoding, fix FingerprintApplicator/DeviceContext kwargs
# 1.18.2 - Fix TCP stack fingerprinting in OPC UA/DNP3/IEC104/SLMP/FINS engines; BACnet/SNMP engine robustness for missing identity data
# 1.18.1 - Ambient SNMP discovery: periodic GET/Response for devices with SNMP protocol (CV fingerprints EWON/gateway devices)
# 1.18.0 - Fix protocol alias mapping: profisafe→profinet, s7comm_plus→s7comm, cip_safety→ethernet_ip; add scenario_id/device_name to DeviceContext
# 1.17.1 - Fix EtherNet/IP product_name: preserve template catalog string, stop overwriting with device_name
# 1.17.0 - Fix CV fingerprinting: CIP identity queries in TCP startup (timing race fix), EWON cloud field mismatch, product_name in all EtherNet/IP templates
# 1.16.0 - Fix CV fingerprinting: EtherNet/IP encapsulation header (28→24 bytes), S7 SZL + Modbus MEI in startup, BACnet firmware_revision merging
# 1.15.2 - Fix double-counted "unknown" protocol stats for ambient/attack packets
# 1.15.1 - Fix SNMP coldStart trap crash: map trap type names to numeric OIDs for Scapy ASN.1 encoding
# 1.15.0 - Broadcast/multicast ecosystem: LLDP, STP, DHCP, BACnet Who-Is, PROFINET DCP, SNMP traps, CDP, IGMP
# 1.14.0 - Process simulation engine: correlated sensor values with ODE models, state machine, 4 vertical templates
# 1.13.0 - Unified TCP builder, staggered flow startup, PROFINET AR establishment (RPC Connect/Write/Control)
# 1.12.0 - PayloadGenerator auto-wiring (realistic sensor values), background noise engine (ARP, NTP)
# 1.11.0 - Live attack simulation: attack playbook execution, kill-chain stage commands (START/STOP/ADVANCE/PAUSE_ATTACK)
# 1.10.0 - Deployment phase scheduling: sequential lifecycle phase cycling (startup → steady → maintenance → shutdown)
# 1.9.0 - Adaptive traffic: server-directed adaptation (ADAPT_TRAFFIC command, directive delivery)
# 1.8.0 - Adaptive traffic: time-of-day traffic scheduling (macro rate shaping, schedule presets)
# 1.7.0 - Adaptive traffic: micro-variations (timing drift, retransmits, vendor personality, connection resets)
# 1.6.0 - Agent health: exponential reconnect backoff (5s->120s cap), scenario thread liveness checks
# 1.5.0 - Live Traffic Dashboard: per-protocol stats, bytes tracking, packet rates, running_scenarios in heartbeat
# 1.4.2 - Synced PROTOCOL_TO_IDENTITY_KEY with canonical source (added enip, s7, bacnet_ip, opc_ua, dnp3, iec104 aliases)
# 1.4.1 - Fixed NameError in PROFINET DCP response (device.device_id -> src.device_id)
# 1.4.0 - Added fingerprint identity support for OPC UA, IEC104, and DNP3 protocols
# 1.3.0 - Added CDP/LLDP discovery for Cisco switches, fixed BACnet unicast polling, fixed protocol port mappings
# 1.2.5 - Simplified updater (no script file), fixed rw mount for self-update
# 1.2.4 - Fixed updater to use alpine with docker-cli-compose (docker:cli not available)
# 1.2.3 - Fixed self-update to spawn external updater container (survives container stop)
# 1.2.2 - Fixed self-update to use down+up instead of force-recreate (avoids name conflicts)
# 1.2.1 - Fixed self-update to mount install directory for docker compose recreate
# 1.2.0 - Added CloudTrafficScheduler for cloud service heartbeats (Talk2M, TeamViewer)
# 1.1.17 - Simplified HTTPS poll logging with !!! markers
# 1.1.15 - Added event loop debug logging for HTTPS flow poll events
# 1.1.14 - Added debug logging for HTTPS external flows
# 1.1.13 - Added Docker CLI to container for self-update support
# 1.1.12 - Fixed BER integer encoding for negative values (ESS temperature readings)
# 1.1.11 - Fixed external flow handling in orchestrator_pool (allow flows without target device)
# 1.1.10 - Added HTTPS external flow support for EWON Talk2M cloud communication
# 1.1.9 - Fixed ALL DeviceContext creations to pass device_name for unique SNMP/PROFINET identities
# 1.1.8 - Made self-update resilient to different install paths (auto-detect or docker restart fallback)
# 1.1.7 - Fixed SNMP sysName and PROFINET station_name to use device_name for unique identification
# 1.1.6 - Added VENDOR_IDENTIFIER polling for BACnet CV detection, increased poll limit to 4
# 1.1.5 - Added device_name and scenario_id fields to DeviceContext
# 1.1.4 - Fixed self-update to use docker compose (restart doesn't pick up new images)
# 1.1.3 - Fixed scenario_id reference error in orchestrator_pool
# 1.1.2 - Fixed device naming for Cyber Vision (PROFINET station_name from device_name)
# 1.1.1 - Fixed fingerprint field name compatibility (fingerprint vs vendor_fingerprint)
# 1.1.0 - Added self-update capability via UPDATE_AGENT command
# 1.0.0 - Initial release with WebSocket-based command/control
