"""Initial migration

Revision ID: 2edadfaf14a4
Revises: 
Create Date: 2025-12-07 18:14:59.349392
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2edadfaf14a4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("supported_protocols", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timing_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload_templates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("behavior_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("vendor_fingerprint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("vertical_hints", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_profiles_device_type"), "device_profiles", ["device_type"], unique=False
    )
    op.create_table(
        "protocol_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("protocol", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("vertical", sa.String(length=50), nullable=True),
        sa.Column("config_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("default_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_protocol_templates_protocol"), "protocol_templates", ["protocol"], unique=False
    )
    op.create_index(
        op.f("ix_protocol_templates_vertical"), "protocol_templates", ["vertical"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "scenarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("vertical", sa.String(length=50), nullable=True),
        sa.Column("total_duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("addressing_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenarios_user_id"), "scenarios", ["user_id"], unique=False)
    op.create_index(op.f("ix_scenarios_vertical"), "scenarios", ["vertical"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_settings_category"), "system_settings", ["category"], unique=False
    )
    op.create_index(op.f("ix_system_settings_key"), "system_settings", ["key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_settings_key"), table_name="system_settings")
    op.drop_index(op.f("ix_system_settings_category"), table_name="system_settings")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_scenarios_vertical"), table_name="scenarios")
    op.drop_index(op.f("ix_scenarios_user_id"), table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_protocol_templates_vertical"), table_name="protocol_templates")
    op.drop_index(op.f("ix_protocol_templates_protocol"), table_name="protocol_templates")
    op.drop_table("protocol_templates")
    op.drop_index(op.f("ix_device_profiles_device_type"), table_name="device_profiles")
    op.drop_table("device_profiles")
    # ### end Alembic commands ###
