#!/usr/bin/env bash
# Regenerate THIRD_PARTY_LICENSES.md from backend (Python) and frontend (npm)
# dependencies. Safe to re-run — the file is overwritten in place.
#
# Usage: run from the repo root.
#   ./scripts/generate_third_party_licenses.sh
#
# The output is linked from the About modal and shipped inside the release
# tarball so downstream users receive all required OSS attribution texts.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
OUT="${REPO_ROOT}/THIRD_PARTY_LICENSES.md"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

[[ -f LICENSE && -f NOTICE ]] || {
    echo "ERROR: LICENSE/NOTICE not found; run from repo root" >&2
    exit 1
}

cat > "$OUT" <<EOF
# Third-Party Licenses

PacketArch is licensed under GPL-3.0 (see [LICENSE](LICENSE) and [NOTICE](NOTICE)).
PacketArch bundles and depends on third-party open-source software listed
below. Each component remains under its own respective license; this file
reproduces attribution as required by those licenses.

> Regenerated by \`scripts/generate_third_party_licenses.sh\` on ${TS}.

---

## Python dependencies (backend)

EOF

# -------- Python side --------
(
    cd "${REPO_ROOT}/backend"
    if ! command -v poetry >/dev/null 2>&1; then
        echo "_poetry not found on PATH; skipped Python attribution._" >> "$OUT"
    else
        if ! poetry run pip-licenses --version >/dev/null 2>&1; then
            echo "Installing pip-licenses in the poetry env..." >&2
            poetry run pip install --quiet pip-licenses
        fi
        poetry run pip-licenses \
            --format=markdown \
            --with-urls \
            --with-authors \
            --order=name \
            >> "$OUT"
    fi
) || echo "_Python attribution failed; please regenerate._" >> "$OUT"

cat >> "$OUT" <<'EOF'

---

## Node dependencies (frontend, production only)

EOF

# -------- Node side --------
(
    cd "${REPO_ROOT}/frontend"
    if [[ ! -d node_modules ]]; then
        echo "_frontend/node_modules not present; run \`pnpm install\` first._" >> "$OUT"
    else
        # license-checker-rseidelsohn is a maintained fork of license-checker
        # with markdown output; npx auto-installs on demand.
        npx --yes license-checker-rseidelsohn \
            --production \
            --markdown \
            --excludePrivatePackages \
            2>/dev/null >> "$OUT" || echo "_license-checker failed._" >> "$OUT"
    fi
) || echo "_Node attribution failed; please regenerate._" >> "$OUT"

cat >> "$OUT" <<'EOF'

---

## Notes

- GPL-2.0 components (notably **Scapy**) are the reason PacketArch as a
  whole is distributed under GPL-3.0.
- Pure-copyleft (GPL/AGPL/LGPL) dependencies cannot be swapped to
  permissive licenses without re-licensing the enclosing project.
- If a dependency is missing here, re-run this script after installing
  dev dependencies in both `backend/` (poetry) and `frontend/` (pnpm).
EOF

echo "Wrote ${OUT}"
