/**
 * Client-side Purdue adjacency conduit generation.
 * Mirrors backend conduit_service.generate_default_conduits().
 */

import type { ScenarioZone, ScenarioConduit, ProtocolType } from '../types';

/** Purdue level adjacency pairs */
const PURDUE_ADJACENCY: [number, number][] = [
  [0, 1],
  [1, 2],
  [2, 3],
  [3, 3.5],
  [3.5, 4],
];

/** Default allowed protocols per Purdue level pair */
const DEFAULT_CONDUIT_PROTOCOLS: Record<string, ProtocolType[]> = {
  '0-1': ['profinet', 'ethernet_ip', 'modbus_tcp', 'bacnet'] as ProtocolType[],
  '1-2': ['s7comm', 'ethernet_ip', 'modbus_tcp', 'profinet', 'bacnet', 'snmp'] as ProtocolType[],
  '2-3': ['modbus_tcp', 'ethernet_ip', 's7comm', 'snmp', 'bacnet'] as ProtocolType[],
  '3-3.5': ['snmp'] as ProtocolType[],
  '3.5-4': ['snmp'] as ProtocolType[],
};

function pairKey(a: number, b: number): string {
  const sorted = [a, b].sort((x, y) => x - y);
  return `${sorted[0]}-${sorted[1]}`;
}

/**
 * Generate default conduits from Purdue level adjacency.
 * @param zones Zone record from scenario store.
 * @param existingConduits Existing conduits to skip duplicates.
 * @returns Array of new ScenarioConduit objects.
 */
export function generatePurdueConduits(
  zones: Record<string, ScenarioZone>,
  existingConduits: Record<string, ScenarioConduit>,
): ScenarioConduit[] {
  const zoneList = Object.values(zones);
  const newConduits: ScenarioConduit[] = [];

  // Build set of existing zone pairs to avoid duplicates
  const existingPairs = new Set<string>();
  for (const conduit of Object.values(existingConduits)) {
    const pair = [conduit.sourceZoneId, conduit.targetZoneId].sort().join('::');
    existingPairs.add(pair);
  }

  // Check each zone pair for Purdue adjacency
  for (let i = 0; i < zoneList.length; i++) {
    for (let j = i + 1; j < zoneList.length; j++) {
      const zoneA = zoneList[i];
      const zoneB = zoneList[j];

      // Need Purdue levels (stored in zone.level)
      const levelA = zoneA.level;
      const levelB = zoneB.level;

      if (levelA == null || levelB == null) continue;

      // Check adjacency
      const isAdjacent = PURDUE_ADJACENCY.some(
        ([a, b]) => (levelA === a && levelB === b) || (levelA === b && levelB === a),
      );

      if (!isAdjacent) continue;

      // Check for existing conduit on this pair
      const pair = [zoneA.id, zoneB.id].sort().join('::');
      if (existingPairs.has(pair)) continue;

      // Get default protocols
      const key = pairKey(levelA, levelB);
      const protocols = DEFAULT_CONDUIT_PROTOCOLS[key] || ['snmp' as ProtocolType];

      // Create conduit (lower level zone as source)
      const [sourceZone, targetZone] = levelA <= levelB ? [zoneA, zoneB] : [zoneB, zoneA];

      const conduitId = `conduit_${sourceZone.id}_${targetZone.id}`;
      newConduits.push({
        id: conduitId,
        name: `${sourceZone.name} \u2194 ${targetZone.name}`,
        sourceZoneId: sourceZone.id,
        targetZoneId: targetZone.id,
        direction: 'bidirectional',
        allowedProtocols: protocols,
        securityLevel: levelA >= 3 || levelB >= 3 ? 'critical' : 'high',
        autoGenerated: true,
      });

      existingPairs.add(pair);
    }
  }

  return newConduits;
}
